In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('large_messy_dataset_option2.csv')

In [3]:
df.head(3)

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023

In [4]:
df.tail()

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
295,11,karan,-3.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,0.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,NaN,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   300 non-null    int64
 1   Name         300 non-null    object
 2   Age          225 non-null    float64
 3   Salary       227 non-null    object
 4   City         251 non-null    object
 5   Email        300 non-null    object
 6   JoiningDate  234 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 16.5+ KB

In [6]:
df.describe()

       CustomerID         Age
count  300.000000  225.000000
mean   114.746667   10.746667
std     80.658385   19.774009
min      0.000000   -3.000000
25%     45.750000   -3.000000
50%    101.000000    0.000000
75%    156.250000   25.000000
max    299.000000   59.000000

In [7]:
df.isnull().sum()

CustomerID      0
Name            0
Age            75
Salary         73
City           49
Email           0
JoiningDate    66
dtype: int64

In [8]:
df.dropna()

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
5,5,Simran,-3.0,Not Available,Chandigarh,simran14@gmail.com,2023/04/20
7,7,Priya,-3.0,-10000,Bangalore,priya42@gmail.com,March 10 2023
8,35,raj,0.0,-10000,Chandigarh,raj15@gmail.com,2023-01-15
9,119,Aman,0.0,98172,Bangalore,aman25@gmail.com,2023/04/20
...,...,...,...,...,...,...,...
286,46,Karan,29.0,-10000,Kolkata,karan3@gmail.com,2023/04/20
289,25,Anjali,0.0,Not Available,Kolkata,anjali25@gmail.com,2023/04/20
290,18,simran,-3.0,Not Available,Chandigarh,simran7@gmail.com,15/02/2023
296,88,anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,0.0,-10000,Kolkata,simran16@gmail.com,2023-01-15

In [9]:
pd.to_numeric(df['Salary'], errors='coerce')

0      116530.0
1           NaN
2      -10000.0
3      -10000.0
4      112349.0
         ...
295         NaN
296     39808.0
297    -10000.0
298    -10000.0
299         NaN
Name: Salary, Length: 300, dtype: float64

In [10]:
df['Salary']=pd.to_numeric(df['Salary'], errors='coerce')

In [11]:
df

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530.0,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000.0,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000.0,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349.0,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,11,karan,-3.0,NaN,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54.0,39808.0,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,0.0,-10000.0,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,-10000.0,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,NaN,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [12]:
df['Salary']=df['Salary'].abs()

In [13]:
df.describe()

       CustomerID         Age         Salary
count  300.000000  225.000000     152.000000
mean   114.746667   10.746667   38273.750000
std     80.658385   19.774009   36837.249772
min      0.000000   -3.000000   10000.000000
25%     45.750000   -3.000000   10000.000000
50%    101.000000    0.000000   10000.000000
75%    156.250000   25.000000   66370.000000
max    299.000000   59.000000  119613.000000

In [14]:
df['Salary'].isnull().sum()

148

In [15]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())

In [16]:
df['Salary'].mean()

38273.75

In [17]:
df['Salary'].median()

38273.75

In [18]:
df['Salary'].mode()

0    38273.75
Name: Salary, dtype: float64

In [19]:
df.describe()

       CustomerID         Age         Salary
count  300.000000  225.000000     300.000000
mean   114.746667   10.746667   38273.750000
std     80.658385   19.774009   26178.217897
min      0.000000   -3.000000   10000.000000
25%     45.750000   -3.000000   10000.000000
50%    101.000000    0.000000   38273.750000
75%    156.250000   25.000000   38273.750000
max    299.000000   59.000000  119613.000000

In [20]:
df[(df['Salary']>=10000) & (df['Salary']<=25000)]

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
2,2,Anjali,NaN,10000.0,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,10000.0,Kolkata,riya8@gmail.com,2023/04/20
7,7,Priya,-3.0,10000.0,Bangalore,priya42@gmail.com,March 10 2023
8,35,raj,0.0,10000.0,Chandigarh,raj15@gmail.com,2023-01-15
13,13,simran,23.0,10000.0,Delhi,simran49@gmail.com,15/02/2023
...,...,...,...,...,...,...,...
286,46,Karan,29.0,10000.0,Kolkata,karan3@gmail.com,2023/04/20
291,291,rohit,-3.0,10000.0,NaN,rohit2@gmail.com,2023/04/20
294,101,anjali,-3.0,10000.0,Delhi,anjali20@gmail.com,NaN
297,121,Simran,0.0,10000.0,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,10000.0,Mumbai,rohit11@gmail.com,15/02/2023

In [21]:
df[df['Salary']==10000]

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
2,2,Anjali,NaN,10000.0,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,10000.0,Kolkata,riya8@gmail.com,2023/04/20
7,7,Priya,-3.0,10000.0,Bangalore,priya42@gmail.com,March 10 2023
8,35,raj,0.0,10000.0,Chandigarh,raj15@gmail.com,2023-01-15
13,13,simran,23.0,10000.0,Delhi,simran49@gmail.com,15/02/2023
...,...,...,...,...,...,...,...
286,46,Karan,29.0,10000.0,Kolkata,karan3@gmail.com,2023/04/20
291,291,rohit,-3.0,10000.0,NaN,rohit2@gmail.com,2023/04/20
294,101,anjali,-3.0,10000.0,Delhi,anjali20@gmail.com,NaN
297,121,Simran,0.0,10000.0,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,10000.0,Mumbai,rohit11@gmail.com,15/02/2023

In [22]:
modes=df['Salary'].mode()

In [23]:
modes

0    38273.75
Name: Salary, dtype: float64

In [24]:
print(modes)

0    38273.75
Name: Salary, dtype: float64

In [25]:
df['Salary'].value_counts()[lambda x: x>1]

Salary
38273.75    148
10000.00     86
Name: count, dtype: int64

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   300 non-null    int64
 1   Name         300 non-null    object
 2   Age          225 non-null    float64
 3   Salary       300 non-null    float64
 4   City         251 non-null    object
 5   Email        300 non-null    object
 6   JoiningDate  234 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 16.5+ KB

In [27]:
df['Age']=df['Age'].abs()

In [28]:
df['Age'].mean()

12.826666666666666

In [29]:
df.loc[df['Age']>20, 'Age'].mean()

39.621212121212125

In [30]:
age_mean=df.loc[df['Age']>20, 'Age'].mean()

In [31]:
age_mean

39.621212121212125

In [32]:
df.loc[(df['Age']>=0) & (df['Age']<=19), 'Age']=age_mean

In [33]:
df['Age']=df['Age'].fillna(39.62)

In [34]:
df['Age'].mean()

39.620909090909095

In [35]:
df['Age']=df['Age'].round()

In [36]:
df['Age']=df['Age'].astype(int)

In [37]:
df

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,40,116530.00,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32,38273.75,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,40,10000.00,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,40,10000.00,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,40,112349.00,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,11,karan,40,38273.75,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54,39808.00,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,40,10000.00,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,40,10000.00,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,40,38273.75,Kolkata,aman17@gmail.com,2023-01-15

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   300 non-null    int64
 1   Name         300 non-null    object
 2   Age          300 non-null    int32
 3   Salary       300 non-null    float64
 4   City         251 non-null    object
 5   Email        300 non-null    object
 6   JoiningDate  234 non-null    object
dtypes: float64(1), int32(1), int64(1), object(4)
memory usage: 15.4+ KB

In [39]:
df['City'].isnull().sum()

49

In [40]:
city_null=df[df['City'].isnull()]

In [41]:
city_null

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,40,116530.00,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32,38273.75,NaN,rohit42@gmail.com,15/02/2023
6,6,Raj,40,38273.75,NaN,raj21@gmail.com,2023-01-15
11,11,Aman,40,86542.00,NaN,aman20@gmail.com,15/02/2023
14,102,Anjali,40,38273.75,NaN,anjali20@gmail.com,NaN
18,18,Priya,21,10000.00,NaN,priya22@gmail.com,15/02/2023
26,34,Karan,59,38273.75,NaN,karan7@gmail.com,2023-01-15
33,33,Karan,40,10000.00,NaN,karan35@gmail.com,2023-01-15
36,129,rohit,40,106951.00,NaN,rohit20@gmail.com,NaN
37,44,Priya,40,10000.00,NaN,priya48@gmail.com,NaN
39,39,riya,40,38273.75,NaN,riya20@gmail.com,15/02/2023
40,49,aman,57,10000.00,NaN,aman37@gmail.com,NaN
43,133,Anjali,40,38273.75,NaN,anjali18@gmail.com,15/02/2023
47,47,Simran,49,38273.75,NaN,simran44@gmail.com,NaN
53,17,Riya,40,10000.00,NaN,riya24@gmail.com,2023-01-15
71,73,Priya,40,10000.00,NaN,priya32@gmail.com,2023/04/20
72,118,Aman,38,72976.00,NaN,aman35@gmail.com,2023-01-15
82,82,Simran,24,38273.75,NaN,simran20@gmail.com,March 10 2023
88,10,priya,40,102345.00,NaN,priya42@gmail.com,NaN
95,55,Raj,40,56666.00,NaN,raj24@gmail.com,NaN
101,125,Karan,40,10000.00,NaN,karan7@gmail.com,2023-01-15
104,104,Rohit,40,38273.75,NaN,rohit31@gmail.com,2023-01-15
115,22,karan,40,10000.00,NaN,karan24@gmail.com,2023-01-15
123,123,Raj,40,64350.00,NaN,raj42@gmail.com,March 10 2023
125,125,rohit,40,10000.00,NaN,rohit22@gmail.com,NaN
137,137,Aman,40,38273.75,NaN,aman2@gmail.com,March 10 2023
140,73,Karan,40,53202.00,NaN,karan13@gmail.com,2023-01-15
149,140,Raj,40,38273.75,NaN,raj5@gmail.com,March 10 2023
154,154,Priya,36,38273.75,NaN,priya36@gmail.com,March 10 2023
156,156,Karan,44,38273.75,NaN,karan20@gmail.com,NaN
170,67,Rohit,40,38273.75,NaN,rohit50@gmail.com,15/02/2023
171,125,simran,40,38273.75,NaN,simran46@gmail.com,NaN
174,174,karan,40,51779.00,NaN,karan34@gmail.com,2023-01-15
181,181,Anjali,37,38273.75,NaN,anjali16@gmail.com,NaN
185,185,raj,46,38273.75,NaN,raj38@gmail.com,2023/04/20
189,189,Raj,40,38273.75,NaN,raj15@gmail.com,March 10 2023
193,56,Priya,40,38273.75,NaN,priya34@gmail.com,March 10 2023
198,198,Simran,40,44906.00,NaN,simran49@gmail.com,2023/04/20
223,223,Aman,52,38273.75,NaN,aman43@gmail.com,2023/04/20
229,50,Rohit,40,71849.00,NaN,rohit40@gmail.com,2023/04/20
243,117,Karan,40,62898.00,NaN,karan6@gmail.com,2023-01-15
247,59,Priya,40,38273.75,NaN,priya45@gmail.com,2023-01-15
250,38,raj,40,38273.75,NaN,raj14@gmail.com,2023/04/20
252,252,Priya,59,38273.75,NaN,priya2@gmail.com,2023/04/20
257,257,Priya,59,10000.00,NaN,priya16@gmail.com,2023-01-15
259,259,Anjali,40,38273.75,NaN,anjali50@gmail.com,2023-01-15
272,272,priya,40,87300.00,NaN,priya20@gmail.com,2023-01-15
291,291,rohit,40,10000.00,NaN,rohit2@gmail.com,2023/04/20
292,292,rohit,40,38273.75,NaN,rohit19@gmail.com,2023-01-15

In [42]:
df.dropna(subset=['City'], inplace=True)

In [43]:
df[df['Email']=='anjali18@gmail.com']

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
2,2,Anjali,40,10000.00,Chandigarh,anjali18@gmail.com,March 10 2023
55,55,Anjali,40,38273.75,Delhi,anjali18@gmail.com,NaN
276,276,anjali,40,38273.75,Chandigarh,anjali18@gmail.com,2023-01-15

In [56]:
city_null.insert(0, 'sr_no', range(1, len(city_null)+1))

In [57]:
city_null

,sr_no,CustomerID,Name,Age,Salary,City,sr_no1,Email,JoiningDate
0,1,0,riya,40,116530.00,NaN,1,riya48@gmail.com,2023/04/20
1,2,139,rohit,32,38273.75,NaN,2,rohit42@gmail.com,15/02/2023
6,3,6,Raj,40,38273.75,NaN,3,raj21@gmail.com,2023-01-15
11,4,11,Aman,40,86542.00,NaN,4,aman20@gmail.com,15/02/2023
14,5,102,Anjali,40,38273.75,NaN,5,anjali20@gmail.com,NaN
18,6,18,Priya,21,10000.00,NaN,6,priya22@gmail.com,15/02/2023
26,7,34,Karan,59,38273.75,NaN,7,karan7@gmail.com,2023-01-15
33,8,33,Karan,40,10000.00,NaN,8,karan35@gmail.com,2023-01-15
36,9,129,rohit,40,106951.00,NaN,9,rohit20@gmail.com,NaN
37,10,44,Priya,40,10000.00,NaN,10,priya48@gmail.com,NaN
39,11,39,riya,40,38273.75,NaN,11,riya20@gmail.com,15/02/2023
40,12,49,aman,57,10000.00,NaN,12,aman37@gmail.com,NaN
43,13,133,Anjali,40,38273.75,NaN,13,anjali18@gmail.com,15/02/2023
47,14,47,Simran,49,38273.75,NaN,14,simran44@gmail.com,NaN
53,15,17,Riya,40,10000.00,NaN,15,riya24@gmail.com,2023-01-15
71,16,73,Priya,40,10000.00,NaN,16,priya32@gmail.com,2023/04/20
72,17,118,Aman,38,72976.00,NaN,17,aman35@gmail.com,2023-01-15
82,18,82,Simran,24,38273.75,NaN,18,simran20@gmail.com,March 10 2023
88,19,10,priya,40,102345.00,NaN,19,priya42@gmail.com,NaN
95,20,55,Raj,40,56666.00,NaN,20,raj24@gmail.com,NaN
101,21,125,Karan,40,10000.00,NaN,21,karan7@gmail.com,2023-01-15
104,22,104,Rohit,40,38273.75,NaN,22,rohit31@gmail.com,2023-01-15
115,23,22,karan,40,10000.00,NaN,23,karan24@gmail.com,2023-01-15
123,24,123,Raj,40,64350.00,NaN,24,raj42@gmail.com,March 10 2023
125,25,125,rohit,40,10000.00,NaN,25,rohit22@gmail.com,NaN
137,26,137,Aman,40,38273.75,NaN,26,aman2@gmail.com,March 10 2023
140,27,73,Karan,40,53202.00,NaN,27,karan13@gmail.com,2023-01-15
149,28,140,Raj,40,38273.75,NaN,28,raj5@gmail.com,March 10 2023
154,29,154,Priya,36,38273.75,NaN,29,priya36@gmail.com,March 10 2023
156,30,156,Karan,44,38273.75,NaN,30,karan20@gmail.com,NaN
170,31,67,Rohit,40,38273.75,NaN,31,rohit50@gmail.com,15/02/2023
171,32,125,simran,40,38273.75,NaN,32,simran46@gmail.com,NaN
174,33,174,karan,40,51779.00,NaN,33,karan34@gmail.com,2023-01-15
181,34,181,Anjali,37,38273.75,NaN,34,anjali16@gmail.com,NaN
185,35,185,raj,46,38273.75,NaN,35,raj38@gmail.com,2023/04/20
189,36,189,Raj,40,38273.75,NaN,36,raj15@gmail.com,March 10 2023
193,37,56,Priya,40,38273.75,NaN,37,priya34@gmail.com,March 10 2023
198,38,198,Simran,40,44906.00,NaN,38,simran49@gmail.com,2023/04/20
223,39,223,Aman,52,38273.75,NaN,39,aman43@gmail.com,2023/04/20
229,40,50,Rohit,40,71849.00,NaN,40,rohit40@gmail.com,2023/04/20
243,41,117,Karan,40,62898.00,NaN,41,karan6@gmail.com,2023-01-15
247,42,59,Priya,40,38273.75,NaN,42,priya45@gmail.com,2023-01-15
250,43,38,raj,40,38273.75,NaN,43,raj14@gmail.com,2023/04/20
252,44,252,Priya,59,38273.75,NaN,44,priya2@gmail.com,2023/04/20
257,45,257,Priya,59,10000.00,NaN,45,priya16@gmail.com,2023-01-15
259,46,259,Anjali,40,38273.75,NaN,46,anjali50@gmail.com,2023-01-15
272,47,272,priya,40,87300.00,NaN,47,priya20@gmail.com,2023-01-15
291,48,291,rohit,40,10000.00,NaN,48,rohit2@gmail.com,2023/04/20
292,49,292,rohit,40,38273.75,NaN,49,rohit19@gmail.com,2023-01-15

In [58]:
city_null.loc[city_null['sr_no']==1, 'City']='Delhi'

In [59]:
def enter_city():
    city=input('enter city name')
    sr_no=int(input('serial'))
    city_null.loc[city_null['sr_no']==sr_no, 'City']=city

In [60]:
value=city_null.loc[city_null['sr_no']==4, 'City']

In [61]:
value=city_null.loc[city_null['sr_no']==5, 'City']

In [62]:
pd.isna(value)

14    True
Name: City, dtype: bool

In [84]:
city_null.reset_index(inplace=True)

In [92]:
mask=(city_null['sr_no'] == 55) & (city_null['City'].isna())

In [93]:
mask

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
dtype: bool

In [79]:
mask.any()

False

In [95]:
def enter_city():
    city = input("Enter city name: ")
    sr_no = int(input("Enter serial number: "))
    
    # Condition: sr_no match AND City is null
    mask = (city_null['sr_no'] == sr_no) & (city_null['City'].isna())
    
    if mask.any():
        city_null.loc[mask, 'City'] = city
        print("City updated successfully ")
    else:
        print("City already exists or invalid serial number ")

In [81]:
enter_city()

Enter city name:  landran
Enter serial number:  1

City already exists or invalid serial number ❌