In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('large_messy_dataset_option2.csv')

In [3]:
df

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,11,karan,-3.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,0.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,NaN,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [6]:
df.rename(columns={'CustomerID':'Student_ID'}, inplace=True)

In [7]:
df

,Student_ID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,11,karan,-3.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,0.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,NaN,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [10]:
df.rename(columns={
    'Student_ID':'S_ID',
    'Age':'Student_Age'
}, inplace=True)

In [11]:
df

,S_ID,Name,Student_Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,11,karan,-3.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,0.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,NaN,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [12]:
df.columns.str.lower()

Index(['s_id', 'name', 'student_age', 'salary', 'city', 'email',
       'joiningdate'],
      dtype='object')

In [13]:
df.columns.str.replace(' ','_')

Index(['S_ID', 'Name', 'Student_Age', 'Salary', 'City', 'Email',
       'JoiningDate'],
      dtype='object')

In [15]:
df['Student_Age'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [16]:
pd.to_numeric(df['Student_Age'], errors='coerce')

0       NaN
1      32.0
2       NaN
3      -3.0
4       NaN
       ...
295    -3.0
296    54.0
297     0.0
298     NaN
299     NaN
Name: Student_Age, Length: 300, dtype: float64

In [19]:
pd.to_datetime(df['JoiningDate'], format="%d/%m/%Y")

ValueError: time data "2023/04/20" doesn't match format "%d/%m/%Y", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [20]:
df

,S_ID,Name,Student_Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,11,karan,-3.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,0.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,NaN,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [22]:
pd.to_datetime(
    df['JoiningDate'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

0     2023-04-20
1     2023-02-15
2     2023-03-10
3     2023-04-20
4     2023-01-15
         ...
295          NaT
296   2023-04-20
297   2023-01-15
298   2023-02-15
299   2023-01-15
Name: JoiningDate, Length: 300, dtype: datetime64[ns]