In [1]:

import pandas as pd

# Load Dataset
df = pd.read_csv("large_messy_dataset_option2.csv")
df.head()

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15

In [2]:

# Rename columns: lowercase and replace spaces with underscore
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.head()

,customerid,name,age,salary,city,email,joiningdate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15

In [3]:

# Convert numeric-like columns safely
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='ignore')

df.dtypes

C:\Users\hitesh\AppData\Local\Temp\ipykernel_10368\978347419.py:3: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')

customerid       int64
name            object
age            float64
salary          object
city            object
email           object
joiningdate     object
dtype: object

In [4]:

# Attempt to convert any column containing 'date' in name
for col in df.columns:
    if 'date' in col:
        df[col] = pd.to_datetime(df[col], format='mixed', dayfirst=True, errors='coerce')

df.head()

,customerid,name,age,salary,city,email,joiningdate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023-04-20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,2023-02-15
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,2023-03-10
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023-04-20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15

In [5]:

# Clean object/string columns
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

df.head()

,customerid,name,age,salary,city,email,joiningdate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023-04-20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,2023-02-15
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,2023-03-10
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023-04-20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15

In [6]:

# Example apply function (if salary column exists)
if 'salary' in df.columns:
    df['bonus_10_percent'] = df['salary'].apply(lambda x: x * 0.10 if pd.notnull(x) else x)

df.head()

TypeError: can't multiply sequence by non-int of type 'float'

In [7]:

# Check missing values
df.isna().sum()

customerid      0
name            0
age            75
salary         73
city           49
email           0
joiningdate    66
dtype: int64

In [8]:

# Save cleaned dataset
df.to_csv("cleaned_large_messy_dataset.csv", index=False)