In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    'name': ['Rahul','Amit'],
    'age': [20,21]
})

df2 = pd.DataFrame({
    'name': ['Neha','Priya'],
    'age': [22,23]
})

In [7]:
pd.concat([df1,df2]).reset_index(drop=True)

    name  age
0  Rahul   20
1   Amit   21
2   Neha   22
3  Priya   23

In [4]:
df1

    name  age
0  Rahul   20
1   Amit   21

In [5]:
df2

    name  age
0   Neha   22
1  Priya   23

In [8]:
pd.concat([df1,df2], axis=1)

    name  age   name  age
0  Rahul   20   Neha   22
1   Amit   21  Priya   23

In [9]:
students = pd.DataFrame({
    "roll":[1,2,3],
    "name":["Rahul","Amit","Neha"]
})

In [10]:
marks = pd.DataFrame({
    "roll":[1,2,3],
    "marks":[85,78,92]
})

In [11]:
df = pd.merge(students, marks, on="roll")
print(df)

   roll   name  marks
0     1  Rahul     85
1     2   Amit     78
2     3   Neha     92

In [17]:
marks2 = pd.DataFrame({
    "roll":[1,2,4],
    "marks":[85,78,56]
})

In [21]:
pd.merge(students, marks2, on="roll", how="outer")

   roll   name  marks
0     1  Rahul   85.0
1     2   Amit   78.0
2     3   Neha    NaN
3     4    NaN   56.0

In [22]:
# pd.merge(students, marks,
#          left_on="roll",
#          right_on="student_id")

In [23]:
df1 = pd.DataFrame({
    "roll":[1,2,3],
    "name":["Rahul","Amit","Neha"],
    "city":["Delhi","Mumbai","Delhi"]
})

In [26]:
df2 = pd.DataFrame({
    "roll":[1,2,3],
    "city":["Delhi","mohali","Pune"],
    "marks":[85,78,90]
})

In [27]:
df = pd.merge(df1, df2, on=["roll","city"])
print(df)

   roll   name   city  marks
0     1  Rahul  Delhi     85

In [28]:
df1

   roll   name    city
0     1  Rahul   Delhi
1     2   Amit  Mumbai
2     3   Neha   Delhi

In [29]:
df2

   roll    city  marks
0     1   Delhi     85
1     2  mohali     78
2     3    Pune     90

In [30]:
df1 = pd.DataFrame({
    "roll":[1,2,3,4,5,6],
    "name":["Rahul","Amit","Neha", "sumit", "lalit", "kamal"]
})

df2 = pd.DataFrame({
    "roll":[1,2,3, 5,6,7],
    "marks":[85,78,92,45,65,67]
})

In [31]:
df11 = df1.set_index("roll")
df22 = df2.set_index("roll")

In [32]:
df11

       name
roll
1     Rahul
2      Amit
3      Neha
4     sumit
5     lalit
6     kamal

In [33]:
df22

      marks
roll
1        85
2        78
3        92
5        45
6        65
7        67

In [35]:
df11.join(df22)

       name  marks
roll
1     Rahul   85.0
2      Amit   78.0
3      Neha   92.0
4     sumit    NaN
5     lalit   45.0
6     kamal   65.0

In [36]:
df11.join(df22, how="inner")

       name  marks
roll
1     Rahul     85
2      Amit     78
3      Neha     92
5     lalit     45
6     kamal     65

In [37]:
df11.join(df22, how="right")

       name  marks
roll
1     Rahul     85
2      Amit     78
3      Neha     92
5     lalit     45
6     kamal     65
7       NaN     67

In [38]:
df11.join(df22, how="outer")

       name  marks
roll
1     Rahul   85.0
2      Amit   78.0
3      Neha   92.0
4     sumit    NaN
5     lalit   45.0
6     kamal   65.0
7       NaN   67.0