In [26]:
import pandas as pd
import numpy as np

In [19]:
df=pd.DataFrame([
    [1,2,3,4,5],
    [11,22,33,44,55],
    [12,21,32,34,54]
]).T

In [20]:
df

   0   1   2
0  1  11  12
1  2  22  21
2  3  33  32
3  4  44  34
4  5  55  54

In [21]:
df2=pd.DataFrame({
    'english':[12,23,34,45],
    'hindi':[34,43,45,65],
    'science':[56,76,78,98]
})

In [22]:
df2

   english  hindi  science
0       12     34       56
1       23     43       76
2       34     45       78
3       45     65       98

In [44]:
df2.index=['aman', 'raman', 'rajan', 'kajal']

In [45]:
df2

       english  hindi  science
aman        12     34       56
raman       23     43       76
rajan       34     45       78
kajal       45     65       98

In [3]:
list1=[22,33,44,55,66,77]
list2=[23,34,45,56,67,78]
list3=[28,37,46,54,63,72]
list4=[list1, list2, list3]

In [4]:
list_data=pd.DataFrame(list4)

In [5]:
list_data

    0   1   2   3   4   5
0  22  33  44  55  66  77
1  23  34  45  56  67  78
2  28  37  46  54  63  72

In [7]:
list_data2=pd.DataFrame(list4).T

In [8]:
list_data2

    0   1   2
0  22  23  28
1  33  34  37
2  44  45  46
3  55  56  54
4  66  67  63
5  77  78  72

In [13]:
subjects=['english', 'hindi', 'punjabi']
list_data2.columns=subjects

In [14]:
list_data2

   english  hindi  punjabi
0       22     23       28
1       33     34       37
2       44     45       46
3       55     56       54
4       66     67       63
5       77     78       72

In [23]:
data = [
    {"Name": "Aman", "Age": 22, "Marks": 85},
    {"Name": "Riya", "Age": 23, "Marks": 90}
]

In [24]:
df3=pd.DataFrame(data)

In [25]:
df3

   Name  Age  Marks
0  Aman   22     85
1  Riya   23     90

In [27]:
new_data=np.array([
    [1,2,3,4,5],
    [11,22,33,44,55],
    [12,13,21,25,45]
])

In [33]:
df4=pd.DataFrame(new_data, columns=['a', 'b', 'c', 'd', 'e'])

In [34]:
df4

    a   b   c   d   e
0   1   2   3   4   5
1  11  22  33  44  55
2  12  13  21  25  45

In [46]:
df5=pd.DataFrame(new_data.T, columns=['a', 'b', 'c'], index=['aman', 'raman', 'saman', 'kamal', 'lalit'])

In [47]:
df5

       a   b   c
aman   1  11  12
raman  2  22  13
saman  3  33  21
kamal  4  44  25
lalit  5  55  45

In [49]:
data_2 = [
    ("Aman", 22),
    ("Riya", 23)
]

df_5 = pd.DataFrame.from_records(data, columns=["Name", "Age"])

In [52]:
df_5

   Name  Age
0  Aman   22
1  Riya   23

In [70]:
names = ["Aman", "Riya"]
ages = [22, 23]

df7 = pd.DataFrame(list(zip(names, ages)), columns=["Name", "Age"])
df8 = pd.DataFrame(list(zip(names, ages)), columns=["Name", "Age"]).T

In [71]:
df7

   Name  Age
0  Aman   22
1  Riya   23

In [72]:
df8

         0     1
Name  Aman  Riya
Age     22    23

In [73]:
names = ["Aman", "Riya"]
ages = [22, 23]

subjects = ['english', 'hindi']

marks = [
    [35,65],
    [65,67]
]

In [75]:
df9 = pd.DataFrame(
    [(name, age, *mark) for name, age, mark in zip(names, ages, marks)],
    columns=["Name", "Age"] + subjects
)

df9

   Name  Age  english  hindi
0  Aman   22       35     65
1  Riya   23       65     67

In [77]:
names = ["Aman", "Riya"]
ages = [22, 23]
subjects = ['english', 'hindi']
marks_aman=[45,54]
marks_riya=[56,76]

In [78]:
marks_total=[marks_aman, marks_riya]

In [81]:
df10=pd.DataFrame(
    [(name, age, *mark) for name, age, mark in zip(names, ages, marks_total)],
    columns=['name', 'age']+subjects
)

In [82]:
df10

   name  age  english  hindi
0  Aman   22       45     54
1  Riya   23       56     76

In [83]:
df11 = pd.DataFrame()

df11["Name"] = ["Aman", "Riya"]
df11["Age"] = [22, 23]

In [84]:
df11

   Name  Age
0  Aman   22
1  Riya   23

In [85]:
df12 = pd.DataFrame({
    "Numbers": range(1,6),
    "Squares": [x**2 for x in range(1,6)]
})

In [86]:
df12

   Numbers  Squares
0        1        1
1        2        4
2        3        9
3        4       16
4        5       25

In [100]:
df.shape

(2, 2)

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

In [98]:
df.head()

   Name  Age
0  Aman   22
1  Riya   23

In [97]:
df.describe()

             Age
count   2.000000
mean   22.500000
std     0.707107
min    22.000000
25%    22.250000
50%    22.500000
75%    22.750000
max    23.000000

In [95]:
df.columns

Index(['Name', 'Age'], dtype='object')

In [96]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [94]:
df.dtypes

Name    object
Age      int64
dtype: object