In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Aman", "Riya", "Karan", "Simran", "Rahul"],
    "Age": [22, 23, 21, 24, 22],
    "City": ["Delhi", "Mumbai", "Delhi", "Chandigarh", "Mumbai"],
    "Marks": [85, 90, 78, 88, 92]
}

In [4]:
df=pd.DataFrame(data)

In [16]:
df.loc[0]

Name      Aman
Age         22
City     Delhi
Marks       85
Name: 0, dtype: object

In [17]:
df.loc[0, "Name"]        # specific value

'Aman'

In [18]:
df.loc[0:2]              # inclusive slicing

    Name  Age    City  Marks
0   Aman   22   Delhi     85
1   Riya   23  Mumbai     90
2  Karan   21   Delhi     78

In [14]:
df.loc[:, "Name"]        # only column

0      Aman
1      Riya
2     Karan
3    Simran
4     Rahul
Name: Name, dtype: object

In [15]:
df.loc[1:3, ["Name","Marks"]]

     Name  Marks
1    Riya     90
2   Karan     78
3  Simran     88

In [22]:
df[df["Age"] > 22]

     Name  Age        City  Marks
1    Riya   23      Mumbai     90
3  Simran   24  Chandigarh     88

In [23]:
df[df["City"] == "Delhi"]

    Name  Age   City  Marks
0   Aman   22  Delhi     85
2  Karan   21  Delhi     78

In [24]:
df[df["Marks"] >= 90]

    Name  Age    City  Marks
1   Riya   23  Mumbai     90
4  Rahul   22  Mumbai     92

In [25]:
df[(df["Age"] > 21) & (df["City"] == "Delhi")]

   Name  Age   City  Marks
0  Aman   22  Delhi     85

In [26]:
df[(df["City"] == "Delhi") | (df["Marks"] > 90)]

    Name  Age    City  Marks
0   Aman   22   Delhi     85
2  Karan   21   Delhi     78
4  Rahul   22  Mumbai     92

In [27]:
df[~(df["City"] == "Delhi")]

     Name  Age        City  Marks
1    Riya   23      Mumbai     90
3  Simran   24  Chandigarh     88
4   Rahul   22      Mumbai     92

In [30]:
df.sort_values("Marks")

     Name  Age        City  Marks
2   Karan   21       Delhi     78
0    Aman   22       Delhi     85
3  Simran   24  Chandigarh     88
1    Riya   23      Mumbai     90
4   Rahul   22      Mumbai     92

In [31]:
df.sort_values("Marks", ascending=False)

     Name  Age        City  Marks
4   Rahul   22      Mumbai     92
1    Riya   23      Mumbai     90
3  Simran   24  Chandigarh     88
0    Aman   22       Delhi     85
2   Karan   21       Delhi     78

In [34]:
df.sort_values(["City", "Marks"])

     Name  Age        City  Marks
3  Simran   24  Chandigarh     88
2   Karan   21       Delhi     78
0    Aman   22       Delhi     85
1    Riya   23      Mumbai     90
4   Rahul   22      Mumbai     92

In [33]:
df.sort_values(["City", "Marks"], ascending=[True, False])

     Name  Age        City  Marks
3  Simran   24  Chandigarh     88
0    Aman   22       Delhi     85
2   Karan   21       Delhi     78
4   Rahul   22      Mumbai     92
1    Riya   23      Mumbai     90

In [35]:
df.sort_values("Marks", inplace=True)