In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('US_honey_dataset_updated.csv')

In [3]:
df['state'].unique()

array(['Alabama', 'Arizona', 'Arkansas', 'California', 'Colorado',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana',
       'Nebraska', 'Nevada', 'NewJersey', 'NewMexico', 'NewYork',
       'NorthCarolina', 'NorthDakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'SouthCarolina', 'SouthDakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'WestVirginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [4]:
df['state'].nunique()

44

In [5]:
for i in df['state'].unique():
    print(i)

Alabama
Arizona
Arkansas
California
Colorado
Florida
Georgia
Hawaii
Idaho
Illinois
Indiana
Iowa
Kansas
Kentucky
Louisiana
Maine
Maryland
Michigan
Minnesota
Mississippi
Missouri
Montana
Nebraska
Nevada
NewJersey
NewMexico
NewYork
NorthCarolina
NorthDakota
Ohio
Oklahoma
Oregon
Pennsylvania
SouthCarolina
SouthDakota
Tennessee
Texas
Utah
Vermont
Virginia
Washington
WestVirginia
Wisconsin
Wyoming

In [7]:
df.groupby('state')['production'].sum()

state
Alabama           14467000
Arizona           38844000
Arkansas          51846000
California       423876000
Colorado          32660000
Florida          280934000
Georgia           57426000
Hawaii            15420000
Idaho             87188000
Illinois           9864000
Indiana            9686000
Iowa              48607000
Kansas            14138000
Kentucky           3224000
Louisiana         60568000
Maine              4762000
Maryland           1975000
Michigan         101063000
Minnesota        176581000
Mississippi       21235000
Missouri          17904000
Montana          197173000
Nebraska          63655000
Nevada             7399000
NewJersey          6913000
NewMexico         10082000
NewYork           78444000
NorthCarolina      8909000
NorthDakota      513742000
Ohio              22485000
Oklahoma           2055000
Oregon            43789000
Pennsylvania      21370000
SouthCarolina      2823000
SouthDakota      355726000
Tennessee          6857000
Texas            129441000
Utah              20369000
Vermont            7032000
Virginia           5153000
Washington        53238000
WestVirginia       6411000
Wisconsin         99909000
Wyoming           43921000
Name: production, dtype: int64

In [8]:
df.groupby('state').sum()

,Unnamed: 0,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
state,,,,,,,,
Alabama,14784,288000,1615,14467000,2987000,4057.61,28668000,54216
Arizona,14811,854000,1490,38844000,17758000,2978.77,59772000,54216
Arkansas,14838,908000,1886,51846000,20897000,2870.45,73781000,54216
California,14865,10135000,1426,423876000,137611000,2954.06,653982000,54216
Colorado,14892,799000,1520,32660000,18695000,3200.56,63844000,54216
Florida,14919,5528000,1956,280934000,47037000,2967.52,509670000,54216
Georgia,14946,1917000,1354,57426000,9932000,3260.68,145945000,54216
Hawaii,14973,296000,2802,15420000,3508000,3719.13,49888000,54216
Idaho,15000,2705000,1121,87188000,40503000,2869.71,139536000,54216
Illinois,15027,236000,1562,9864000,4957000,5842.43,36782000,54216
Indiana,15054,213000,1605,9686000,5286000,4183.16,24658000,54216
Iowa,15081,962000,1659,48607000,29351000,3341.75,87563000,54216
Kansas,15108,301000,1570,14138000,7520000,3977.44,27970000,54216
Kentucky,14731,113000,1260,3224000,1128000,5250.45,15427000,52212
Louisiana,15161,1066000,2506,60568000,12688000,2783.02,129601000,54216
Maine,15188,252000,888,4762000,2271000,4691.80,19842000,54216
Maryland,1708,48000,377,1975000,477000,1310.00,2735000,17991
Michigan,15224,2168000,1753,101063000,58401000,3311.97,217841000,54216
Minnesota,15251,3498000,1885,176581000,51908000,2887.89,310462000,54216
Mississippi,15278,485000,2341,21235000,6799000,2776.70,59265000,54216
Missouri,15305,390000,1460,17904000,4870000,3941.76,32372000,54216
Montana,15332,3725000,2148,197173000,91240000,2961.17,406563000,54216
Nebraska,15359,1279000,1729,63655000,38937000,3004.31,106998000,54216
Nevada,4858,157000,700,7399000,1935000,3068.00,14520000,30030
NewJersey,15401,299000,958,6913000,3311000,5262.74,28201000,54216
NewMexico,6985,185000,1010,10082000,4561000,2197.00,11049000,36063
NewYork,15446,1588000,1745,78444000,42535000,3663.52,177921000,54216
NorthCarolina,15473,304000,1236,8909000,3101000,5540.21,38645000,54216
NorthDakota,15500,10710000,2266,513742000,206707000,2863.08,1186219000,54216
Ohio,15527,449000,1763,22485000,13269000,4417.38,59637000,54216
Oklahoma,1834,40000,471,2055000,693000,1203.00,2618000,17991
Oregon,15563,1594000,1145,43789000,28655000,3221.40,102109000,54216
Pennsylvania,15590,586000,1317,21370000,11339000,4130.82,55153000,54216
SouthCarolina,8538,148000,727,2823000,486000,2111.96,26218000,24136
SouthDakota,15629,6639000,1950,355726000,218634000,2891.51,619095000,54216
Tennessee,15656,189000,1497,6857000,2460000,5318.06,27276000,54216
Texas,15683,2876000,1921,129441000,41022000,2965.74,284720000,54216
Utah,15710,719000,1130,20369000,6775000,3003.27,40157000,54216
Vermont,15737,149000,1674,7032000,3489000,4689.46,19084000,54216
Virginia,15764,170000,1097,5153000,1809000,6419.69,20925000,54216
Washington,15791,1709000,1255,53238000,28500000,3208.36,119823000,54216
WestVirginia,15818,179000,1245,6411000,3034000,5162.20,18685000,54216
Wisconsin,15845,1698000,1896,99909000,59166000,3410.87,176442000,54216
Wyoming,15872,1065000,1698,43921000,11235000,2904.12,87502000,54216

In [22]:
df.groupby('state')['production'].agg(['sum','mean','max'])

                     sum        mean       max
state
Alabama         14467000   535814.81   1248000
Arizona         38844000  1438666.67   4108000
Arkansas        51846000  1920222.22   5655000
California     423876000 15699111.11  39060000
Colorado        32660000  1209629.63   2700000
Florida        280934000 10404962.96  25200000
Georgia         57426000  2126888.89   5100000
Hawaii          15420000   571111.11   1314000
Idaho           87188000  3229185.19   7680000
Illinois         9864000   365333.33    814000
Indiana          9686000   358740.74    828000
Iowa            48607000  1800259.26   3900000
Kansas          14138000   523629.63   1207000
Kentucky         3224000   124000.00    280000
Louisiana       60568000  2243259.26   5472000
Maine            4762000   176370.37    495000
Maryland         1975000   219444.44    308000
Michigan       101063000  3743074.07   8924000
Minnesota      176581000  6540037.04  13530000
Mississippi     21235000   786481.48   1575000
Missouri        17904000   663111.11   1848000
Montana        197173000  7302703.70  14030000
Nebraska        63655000  2357592.59   4875000
Nevada           7399000   493266.67    854000
NewJersey        6913000   256037.04    539000
NewMexico       10082000   560111.11   1235000
NewYork         78444000  2905333.33   5880000
NorthCarolina    8909000   329962.96    714000
NorthDakota    513742000 19027481.48  35100000
Ohio            22485000   832777.78   1760000
Oklahoma         2055000   228333.33    380000
Oregon          43789000  1621814.81   3245000
Pennsylvania    21370000   791481.48   1620000
SouthCarolina    2823000   235250.00    810000
SouthDakota    355726000 13175037.04  28435000
Tennessee        6857000   253962.96    549000
Texas          129441000  4794111.11   9964000
Utah            20369000   754407.41   1740000
Vermont          7032000   260444.44    623000
Virginia         5153000   190851.85    468000
Washington      53238000  1971777.78   3540000
WestVirginia     6411000   237444.44    590000
Wisconsin       99909000  3700333.33   8099000
Wyoming         43921000  1626703.70   3627000

In [21]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [15]:
df.groupby(['state','year'])['production'].sum()

state          year
Alabama        1995      928000
               1996     1024000
               1997      924000
               1998     1136000
               1999     1156000
               2000     1248000
               2001     1022000
               2002     1032000
               2003     1066000
               2004     1044000
               2005      858000
               2006      792000
               2007      616000
               2008      594000
               2009      441000
               2010       73000
               2011       63000
               2012       65000
               2013       55000
               2014       26000
               2015       13000
               2016       33000
               2017       22000
               2018       14000
               2019       44000
               2020       66000
               2021      112000
Arizona        1995     4108000
               1996     1920000
               1997     2560000
               1998     3300000
               1999     3224000
               2000     2360000
               2001     2537000
               2002     2394000
               2003     2880000
               2004     1760000
               2005     1800000
               2006     1950000
               2007     1920000
               2008     1600000
               2009     1040000
               2010      665000
               2011      427000
               2012      253000
               2013      251000
               2014      193000
               2015      306000
               2016      261000
               2017       97000
               2018      109000
               2019      201000
               2020      360000
               2021      368000
Arkansas       1995     3000000
               1996     3360000
               1997     3800000
               1998     3445000
               1999     4628000
               2000     5115000
               2001     5655000
               2002     4840000
               2003     3000000
               2004     2280000
               2005     2484000
               2006     2432000
               2007     2240000
               2008     2100000
               2009     1368000
               2010      360000
               2011      239000
               2012      189000
               2013       66000
               2014      137000
               2015      121000
               2016       99000
               2017      197000
               2018       84000
               2019      176000
               2020      176000
               2021      255000
California     1995    39060000
               1996    27300000
               1997    30000000
               1998    37350000
               1999    30300000
               2000    30800000
               2001    27625000
               2002    23320000
               2003    32160000
               2004    17550000
               2005    30000000
               2006    19760000
               2007    13600000
               2008    18360000
               2009    11715000
               2010     6318000
               2011     3730000
               2012     3119000
               2013     2505000
               2014     2995000
               2015     1485000
               2016     2009000
               2017     2198000
               2018     3022000
               2019     3216000
               2020     2752000
               2021     1627000
Colorado       1995     2700000
               1996     2220000
               1997     1925000
               1998     1944000
               1999     2052000
               2000     1740000
               2001     1430000
               2002     1440000
               2003     2064000
               2004     1840000
               2005     1820000
               2006     2700000
               2007     1683000
               2008     1215000
               2009     1484000
               2010      533000
               2011      443000
               2012      468000
               2013      324000
               2014      200000
               2015      399000
               2016      282000
               2017      284000
               2018      283000
               2019      500000
               2020      455000
               2021      232000
Florida        1995    19780000
               1996    25200000
               1997    16080000
               1998    22540000
               1999    23256000
               2000    24360000
               2001    22000000
               2002    20460000
               2003    14910000
               2004    20090000
               2005    13760000
               2006    13770000
               2007    11360000
               2008    11850000
               2009    10200000
               2010     1794000
               2011      988000
               2012     1235000
               2013     1074000
               2014     1029000
               2015      832000
               2016      538000
               2017      529000
               2018      737000
               2019      830000
               2020      883000
               2021      849000
Georgia        1995     4340000
               1996     5100000
               1997     3450000
               1998     4200000
               1999     3315000
               2000     3135000
               2001     3135000
               2002     2600000
               2003     3380000
               2004     3087000
               2005     2891000
               2006     4662000
               2007     3480000
               2008     3905000
               2009     2665000
               2010      152000
               2011      196000
               2012      181000
               2013      637000
               2014      362000
               2015      221000
               2016      899000
               2017      190000
               2018      200000
               2019      370000
               2020      412000
               2021      261000
Hawaii         1995     1032000
               1996     1240000
               1997     1314000
               1998      944000
               1999      640000
               2000      784000
               2001      696000
               2002      952000
               2003      791000
               2004      768000
               2005     1179000
               2006      930000
               2007      920000
               2008      900000
               2009      950000
               2010      239000
               2011      246000
               2012      263000
               2013       65000
               2014      140000
               2015       71000
               2016      127000
               2017       25000
               2018       18000
               2019       51000
               2020       79000
               2021       56000
Idaho          1995     6000000
               1996     4950000
               1997     7680000
               1998     6000000
               1999     5760000
               2000     4700000
               2001     4600000
               2002     5700000
               2003     4600000
               2004     6300000
               2005     3515000
               2006     4180000
               2007     3772000
               2008     3600000
               2009     4738000
               2010     1179000
               2011     1879000
               2012      530000
               2013     1036000
               2014      850000
               2015     1082000
               2016     1253000
               2017     1045000
               2018      655000
               2019      677000
               2020      637000
               2021      270000
Illinois       1995      814000
               1996      814000
               1997      483000
               1998      639000
               1999      594000
               2000      488000
               2001      456000
               2002      720000
               2003      420000
               2004      385000
               2005      680000
               2006      660000
               2007      567000
               2008      448000
               2009      272000
               2010       92000
               2011       98000
               2012      145000
               2013      101000
               2014       94000
               2015      155000
               2016       77000
               2017      167000
               2018      108000
               2019      116000
               2020      156000
               2021      115000
Indiana        1995      756000
               1996      675000
               1997      568000
               1998      828000
               1999      810000
               2000      520000
               2001      608000
               2002      496000
               2003      280000
               2004      413000
               2005      512000
               2006      324000
               2007      357000
               2008      402000
               2009      288000
               2010      151000
               2011      147000
               2012      203000
               2013       82000
               2014      115000
               2015      165000
               2016      208000
               2017      158000
               2018      106000
               2019      188000
               2020      149000
               2021      177000
Iowa           1995     3400000
               1996     3886000
               1997     3774000
               1998     3900000
               1999     2600000
               2000     2010000
               2001     1683000
               2002     2310000
               2003     1888000
               2004     2345000
               2005     2464000
               2006     2184000
               2007     2106000
               2008     1488000
               2009     1092000
               2010      463000
               2011      961000
               2012     1196000
               2013     1217000
               2014      933000
               2015      990000
               2016      746000
               2017     1035000
               2018     1005000
               2019     1170000
               2020     1259000
               2021      502000
Kansas         1995     1139000
               1996      816000
               1997     1207000
               1998      736000
               1999      871000
               2000     1020000
               2001      663000
               2002      884000
               2003      912000
               2004     1120000
               2005      800000
               2006      770000
               2007      560000
               2008      610000
               2009      567000
               2010      103000
               2011      117000
               2012      125000
               2013       39000
               2014       84000
               2015      107000
               2016       54000
               2017      260000
               2018       95000
               2019      171000
               2020      164000
               2021      144000
Kentucky       1995      132000
               1996      180000
               1997      180000
               1998      150000
               1999      150000
               2000      144000
               2001      234000
               2002      162000
               2003      240000
               2005      250000
               2006      280000
               2007      244000
               2008      156000
               2009      175000
               2010       67000
               2011       12000
               2012       41000
               2013       17000
               2014       56000
               2015       55000
               2016       48000
               2017       42000
               2018       34000
               2019       44000
               2020       58000
               2021       73000
Louisiana      1995     3927000
               1996     3922000
               1997     4370000
               1998     4551000
               1999     5472000
               2000     4042000
               2001     4770000
               2002     4340000
               2003     3060000
               2004     3430000
               2005     3395000
               2006     2700000
               2007     2581000
               2008     2233000
               2009     3811000
               2010      288000
               2011      471000
               2012      141000
               2013      490000
               2014      524000
               2015      348000
               2016      301000
               2017      279000
               2018      261000
               2019      428000
               2020      228000
               2021      205000
Maine          1995      495000
               1996      230000
               1997      152000
               1998      260000
               1999      308000
               2000      231000
               2001      220000
               2002      451000
               2003      264000
               2004      217000
               2005      208000
               2006      253000
               2007      234000
               2008      294000
               2009      300000
               2010       33000
               2011       17000
               2012       24000
               2013       27000
               2014       41000
               2015       47000
               2016       65000
               2017       51000
               2018       92000
               2019      110000
               2020       78000
               2021       60000
Maryland       1995      245000
               1996      224000
               1997      240000
               1998      308000
               1999      276000
               2000      276000
               2001      184000
               2002      138000
               2003       84000
Michigan       1995     8924000
               1996     8640000
               1997     5950000
               1998     6800000
               1999     6205000
               2000     5400000
               2001     4560000
               2002     5544000
               2003     4810000
               2004     4355000
               2005     4420000
               2006     3960000
               2007     4608000
               2008     5183000
               2009     3960000
               2010     1524000
               2011     2084000
               2012     1332000
               2013      982000
               2014     1835000
               2015     1984000
               2016     1709000
               2017      822000
               2018      768000
               2019     1363000
               2020     1384000
               2021     1957000
Minnesota      1995    13530000
               1996    11550000
               1997    10585000
               1998    11060000
               1999    11890000
               2000    13500000
               2001    10935000
               2002     8541000
               2003     9960000
               2004    10125000
               2005     8880000
               2006    10000000
               2007     8840000
               2008     9516000
               2009     7930000
               2010     1774000
               2011     2099000
               2012     1591000
               2013     1282000
               2014     1426000
               2015     2157000
               2016     1390000
               2017     1016000
               2018     1161000
               2019     3063000
               2020     2495000
               2021      285000
Mississippi    1995     1120000
               1996     1360000
               1997     1387000
               1998     1548000
               1999     1314000
               2000     1224000
               2001     1122000
               2002     1404000
               2003     1449000
               2004     1170000
               2005     1280000
               2006     1372000
               2007     1575000
               2008     1372000
               2009     1456000
               2010       78000
               2011      104000
               2012       64000
               2013       39000
               2014       45000
               2015       87000
               2016      113000
               2017      124000
               2018       70000
               2019      141000
               2020      146000
               2021       71000
Missouri       1995     1541000
               1996     1628000
               1997     1848000
               1998     1518000
               1999     1560000
               2000     1725000
               2001     1525000
               2002      954000
               2003      901000
               2004      656000
               2005      750000
               2006      690000
               2007      611000
               2008      583000
               2009      517000
               2010       92000
               2011       76000
               2012      108000
               2013       85000
               2014       96000
               2015       52000
               2016       30000
               2017       57000
               2018       36000
               2019       73000
               2020      100000
               2021       92000
Montana        1995     8480000
               1996     7020000
               1997    12840000
               1998    14030000
               1999     8540000
               2000    12728000
               2001    13872000
               2002     8442000
               2003     9570000
               2004    10780000
               2005     8710000
               2006    10428000
               2007     9180000
               2008     9380000
               2009    10220000
               2010     2905000
               2011     3202000
               2012     2413000
               2013     5231000
               2014     5132000
               2015     3757000
               2016     3183000
               2017     2506000
               2018     3680000
               2019     5802000
               2020     3208000
               2021     1934000
Nebraska       1995     4380000
               1996     4875000
               1997     4087000
               1998     4480000
               1999     4466000
               2000     4350000
               2001     2064000
               2002     3225000
               2003     3330000
               2004     4539000
               2005     2720000
               2006     3431000
               2007     2205000
               2008     2412000
               2009     2688000
               2010      902000
               2011      653000
               2012     1146000
               2013     1628000
               2014     1688000
               2015     1450000
               2016      640000
               2017      423000
               2018      850000
               2019      223000
               2020      250000
               2021      550000
Nevada         1995      261000
               1996      854000
               1997      854000
               1998      460000
               1999      383000
               2000      350000
               2001      550000
               2002      558000
               2003      384000
               2004      770000
               2005      552000
               2006      333000
               2007      280000
               2008      290000
               2009      520000
NewJersey      1995      272000
               1996      225000
               1997      392000
               1998      539000
               1999      440000
               2000      385000
               2001      374000

In [17]:
pd.set_option('display.max_rows', None)

In [18]:
df.groupby('state')['production'].sum().reset_index()

            state  production
0         Alabama    14467000
1         Arizona    38844000
2        Arkansas    51846000
3      California   423876000
4        Colorado    32660000
5         Florida   280934000
6         Georgia    57426000
7          Hawaii    15420000
8           Idaho    87188000
9        Illinois     9864000
10        Indiana     9686000
11           Iowa    48607000
12         Kansas    14138000
13       Kentucky     3224000
14      Louisiana    60568000
15          Maine     4762000
16       Maryland     1975000
17       Michigan   101063000
18      Minnesota   176581000
19    Mississippi    21235000
20       Missouri    17904000
21        Montana   197173000
22       Nebraska    63655000
23         Nevada     7399000
24      NewJersey     6913000
25      NewMexico    10082000
26        NewYork    78444000
27  NorthCarolina     8909000
28    NorthDakota   513742000
29           Ohio    22485000
30       Oklahoma     2055000
31         Oregon    43789000
32   Pennsylvania    21370000
33  SouthCarolina     2823000
34    SouthDakota   355726000
35      Tennessee     6857000
36          Texas   129441000
37           Utah    20369000
38        Vermont     7032000
39       Virginia     5153000
40     Washington    53238000
41   WestVirginia     6411000
42      Wisconsin    99909000
43        Wyoming    43921000

In [19]:
df.groupby('state')['value_of_production'].sum().sort_values(ascending=False)

state
NorthDakota      1186219000
California        653982000
SouthDakota       619095000
Florida           509670000
Montana           406563000
Minnesota         310462000
Texas             284720000
Michigan          217841000
NewYork           177921000
Wisconsin         176442000
Georgia           145945000
Idaho             139536000
Louisiana         129601000
Washington        119823000
Nebraska          106998000
Oregon            102109000
Iowa               87563000
Wyoming            87502000
Arkansas           73781000
Colorado           63844000
Arizona            59772000
Ohio               59637000
Mississippi        59265000
Pennsylvania       55153000
Hawaii             49888000
Utah               40157000
NorthCarolina      38645000
Illinois           36782000
Missouri           32372000
Alabama            28668000
NewJersey          28201000
Kansas             27970000
Tennessee          27276000
SouthCarolina      26218000
Indiana            24658000
Virginia           20925000
Maine              19842000
Vermont            19084000
WestVirginia       18685000
Kentucky           15427000
Nevada             14520000
NewMexico          11049000
Maryland            2735000
Oklahoma            2618000
Name: value_of_production, dtype: int64

In [20]:
df.groupby('state').agg({
'production':'sum',
'average_price':'mean',
'value_of_production':'sum'
})

               production  average_price  value_of_production
state
Alabama          14467000     150.281852             28668000
Arizona          38844000     110.324815             59772000
Arkansas         51846000     106.312963             73781000
California      423876000     109.409630            653982000
Colorado         32660000     118.539259             63844000
Florida         280934000     109.908148            509670000
Georgia          57426000     120.765926            145945000
Hawaii           15420000     137.745556             49888000
Idaho            87188000     106.285556            139536000
Illinois          9864000     216.386296             36782000
Indiana           9686000     154.931852             24658000
Iowa             48607000     123.768519             87563000
Kansas           14138000     147.312593             27970000
Kentucky          3224000     201.940385             15427000
Louisiana        60568000     103.074815            129601000
Maine             4762000     173.770370             19842000
Maryland          1975000     145.555556              2735000
Michigan        101063000     122.665556            217841000
Minnesota       176581000     106.958889            310462000
Mississippi      21235000     102.840741             59265000
Missouri         17904000     145.991111             32372000
Montana         197173000     109.672963            406563000
Nebraska         63655000     111.270741            106998000
Nevada            7399000     204.533333             14520000
NewJersey         6913000     194.916296             28201000
NewMexico        10082000     122.055556             11049000
NewYork          78444000     135.685926            177921000
NorthCarolina     8909000     205.192963             38645000
NorthDakota     513742000     106.040000           1186219000
Ohio             22485000     163.606667             59637000
Oklahoma          2055000     133.666667              2618000
Oregon           43789000     119.311111            102109000
Pennsylvania     21370000     152.993333             55153000
SouthCarolina     2823000     175.996667             26218000
SouthDakota     355726000     107.092963            619095000
Tennessee         6857000     196.965185             27276000
Texas           129441000     109.842222            284720000
Utah             20369000     111.232222             40157000
Vermont           7032000     173.683704             19084000
Virginia          5153000     237.766296             20925000
Washington       53238000     118.828148            119823000
WestVirginia      6411000     191.192593             18685000
Wisconsin        99909000     126.328519            176442000
Wyoming          43921000     107.560000             87502000

In [23]:
df.groupby('state').agg(
Total_Production=('production','sum'),
Avg_Price=('average_price','mean'),
Total_Revenue=('value_of_production','sum')
)

               Total_Production  Avg_Price  Total_Revenue
state
Alabama                14467000     150.28       28668000
Arizona                38844000     110.32       59772000
Arkansas               51846000     106.31       73781000
California            423876000     109.41      653982000
Colorado               32660000     118.54       63844000
Florida               280934000     109.91      509670000
Georgia                57426000     120.77      145945000
Hawaii                 15420000     137.75       49888000
Idaho                  87188000     106.29      139536000
Illinois                9864000     216.39       36782000
Indiana                 9686000     154.93       24658000
Iowa                   48607000     123.77       87563000
Kansas                 14138000     147.31       27970000
Kentucky                3224000     201.94       15427000
Louisiana              60568000     103.07      129601000
Maine                   4762000     173.77       19842000
Maryland                1975000     145.56        2735000
Michigan              101063000     122.67      217841000
Minnesota             176581000     106.96      310462000
Mississippi            21235000     102.84       59265000
Missouri               17904000     145.99       32372000
Montana               197173000     109.67      406563000
Nebraska               63655000     111.27      106998000
Nevada                  7399000     204.53       14520000
NewJersey               6913000     194.92       28201000
NewMexico              10082000     122.06       11049000
NewYork                78444000     135.69      177921000
NorthCarolina           8909000     205.19       38645000
NorthDakota           513742000     106.04     1186219000
Ohio                   22485000     163.61       59637000
Oklahoma                2055000     133.67        2618000
Oregon                 43789000     119.31      102109000
Pennsylvania           21370000     152.99       55153000
SouthCarolina           2823000     176.00       26218000
SouthDakota           355726000     107.09      619095000
Tennessee               6857000     196.97       27276000
Texas                 129441000     109.84      284720000
Utah                   20369000     111.23       40157000
Vermont                 7032000     173.68       19084000
Virginia                5153000     237.77       20925000
Washington             53238000     118.83      119823000
WestVirginia            6411000     191.19       18685000
Wisconsin              99909000     126.33      176442000
Wyoming                43921000     107.56       87502000

In [24]:
df.groupby('state')['production'].sum().nlargest(5)

state
NorthDakota    513742000
California     423876000
SouthDakota    355726000
Florida        280934000
Montana        197173000
Name: production, dtype: int64

In [25]:
df.groupby('state')['production'].sum().sort_values(ascending=False)

state
NorthDakota      513742000
California       423876000
SouthDakota      355726000
Florida          280934000
Montana          197173000
Minnesota        176581000
Texas            129441000
Michigan         101063000
Wisconsin         99909000
Idaho             87188000
NewYork           78444000
Nebraska          63655000
Louisiana         60568000
Georgia           57426000
Washington        53238000
Arkansas          51846000
Iowa              48607000
Wyoming           43921000
Oregon            43789000
Arizona           38844000
Colorado          32660000
Ohio              22485000
Pennsylvania      21370000
Mississippi       21235000
Utah              20369000
Missouri          17904000
Hawaii            15420000
Alabama           14467000
Kansas            14138000
NewMexico         10082000
Illinois           9864000
Indiana            9686000
NorthCarolina      8909000
Nevada             7399000
Vermont            7032000
NewJersey          6913000
Tennessee          6857000
WestVirginia       6411000
Virginia           5153000
Maine              4762000
Kentucky           3224000
SouthCarolina      2823000
Oklahoma           2055000
Maryland           1975000
Name: production, dtype: int64

In [26]:
df.groupby(['state','year'])['production'].sum()

state          year
Alabama        1995      928000
               1996     1024000
               1997      924000
               1998     1136000
               1999     1156000
               2000     1248000
               2001     1022000
               2002     1032000
               2003     1066000
               2004     1044000
               2005      858000
               2006      792000
               2007      616000
               2008      594000
               2009      441000
               2010       73000
               2011       63000
               2012       65000
               2013       55000
               2014       26000
               2015       13000
               2016       33000
               2017       22000
               2018       14000
               2019       44000
               2020       66000
               2021      112000
Arizona        1995     4108000
               1996     1920000
               1997     2560000
               1998     3300000
               1999     3224000
               2000     2360000
               2001     2537000
               2002     2394000
               2003     2880000
               2004     1760000
               2005     1800000
               2006     1950000
               2007     1920000
               2008     1600000
               2009     1040000
               2010      665000
               2011      427000
               2012      253000
               2013      251000
               2014      193000
               2015      306000
               2016      261000
               2017       97000
               2018      109000
               2019      201000
               2020      360000
               2021      368000
Arkansas       1995     3000000
               1996     3360000
               1997     3800000
               1998     3445000
               1999     4628000
               2000     5115000
               2001     5655000
               2002     4840000
               2003     3000000
               2004     2280000
               2005     2484000
               2006     2432000
               2007     2240000
               2008     2100000
               2009     1368000
               2010      360000
               2011      239000
               2012      189000
               2013       66000
               2014      137000
               2015      121000
               2016       99000
               2017      197000
               2018       84000
               2019      176000
               2020      176000
               2021      255000
California     1995    39060000
               1996    27300000
               1997    30000000
               1998    37350000
               1999    30300000
               2000    30800000
               2001    27625000
               2002    23320000
               2003    32160000
               2004    17550000
               2005    30000000
               2006    19760000
               2007    13600000
               2008    18360000
               2009    11715000
               2010     6318000
               2011     3730000
               2012     3119000
               2013     2505000
               2014     2995000
               2015     1485000
               2016     2009000
               2017     2198000
               2018     3022000
               2019     3216000
               2020     2752000
               2021     1627000
Colorado       1995     2700000
               1996     2220000
               1997     1925000
               1998     1944000
               1999     2052000
               2000     1740000
               2001     1430000
               2002     1440000
               2003     2064000
               2004     1840000
               2005     1820000
               2006     2700000
               2007     1683000
               2008     1215000
               2009     1484000
               2010      533000
               2011      443000
               2012      468000
               2013      324000
               2014      200000
               2015      399000
               2016      282000
               2017      284000
               2018      283000
               2019      500000
               2020      455000
               2021      232000
Florida        1995    19780000
               1996    25200000
               1997    16080000
               1998    22540000
               1999    23256000
               2000    24360000
               2001    22000000
               2002    20460000
               2003    14910000
               2004    20090000
               2005    13760000
               2006    13770000
               2007    11360000
               2008    11850000
               2009    10200000
               2010     1794000
               2011      988000
               2012     1235000
               2013     1074000
               2014     1029000
               2015      832000
               2016      538000
               2017      529000
               2018      737000
               2019      830000
               2020      883000
               2021      849000
Georgia        1995     4340000
               1996     5100000
               1997     3450000
               1998     4200000
               1999     3315000
               2000     3135000
               2001     3135000
               2002     2600000
               2003     3380000
               2004     3087000
               2005     2891000
               2006     4662000
               2007     3480000
               2008     3905000
               2009     2665000
               2010      152000
               2011      196000
               2012      181000
               2013      637000
               2014      362000
               2015      221000
               2016      899000
               2017      190000
               2018      200000
               2019      370000
               2020      412000
               2021      261000
Hawaii         1995     1032000
               1996     1240000
               1997     1314000
               1998      944000
               1999      640000
               2000      784000
               2001      696000
               2002      952000
               2003      791000
               2004      768000
               2005     1179000
               2006      930000
               2007      920000
               2008      900000
               2009      950000
               2010      239000
               2011      246000
               2012      263000
               2013       65000
               2014      140000
               2015       71000
               2016      127000
               2017       25000
               2018       18000
               2019       51000
               2020       79000
               2021       56000
Idaho          1995     6000000
               1996     4950000
               1997     7680000
               1998     6000000
               1999     5760000
               2000     4700000
               2001     4600000
               2002     5700000
               2003     4600000
               2004     6300000
               2005     3515000
               2006     4180000
               2007     3772000
               2008     3600000
               2009     4738000
               2010     1179000
               2011     1879000
               2012      530000
               2013     1036000
               2014      850000
               2015     1082000
               2016     1253000
               2017     1045000
               2018      655000
               2019      677000
               2020      637000
               2021      270000
Illinois       1995      814000
               1996      814000
               1997      483000
               1998      639000
               1999      594000
               2000      488000
               2001      456000
               2002      720000
               2003      420000
               2004      385000
               2005      680000
               2006      660000
               2007      567000
               2008      448000
               2009      272000
               2010       92000
               2011       98000
               2012      145000
               2013      101000
               2014       94000
               2015      155000
               2016       77000
               2017      167000
               2018      108000
               2019      116000
               2020      156000
               2021      115000
Indiana        1995      756000
               1996      675000
               1997      568000
               1998      828000
               1999      810000
               2000      520000
               2001      608000
               2002      496000
               2003      280000
               2004      413000
               2005      512000
               2006      324000
               2007      357000
               2008      402000
               2009      288000
               2010      151000
               2011      147000
               2012      203000
               2013       82000
               2014      115000
               2015      165000
               2016      208000
               2017      158000
               2018      106000
               2019      188000
               2020      149000
               2021      177000
Iowa           1995     3400000
               1996     3886000
               1997     3774000
               1998     3900000
               1999     2600000
               2000     2010000
               2001     1683000
               2002     2310000
               2003     1888000
               2004     2345000
               2005     2464000
               2006     2184000
               2007     2106000
               2008     1488000
               2009     1092000
               2010      463000
               2011      961000
               2012     1196000
               2013     1217000
               2014      933000
               2015      990000
               2016      746000
               2017     1035000
               2018     1005000
               2019     1170000
               2020     1259000
               2021      502000
Kansas         1995     1139000
               1996      816000
               1997     1207000
               1998      736000
               1999      871000
               2000     1020000
               2001      663000
               2002      884000
               2003      912000
               2004     1120000
               2005      800000
               2006      770000
               2007      560000
               2008      610000
               2009      567000
               2010      103000
               2011      117000
               2012      125000
               2013       39000
               2014       84000
               2015      107000
               2016       54000
               2017      260000
               2018       95000
               2019      171000
               2020      164000
               2021      144000
Kentucky       1995      132000
               1996      180000
               1997      180000
               1998      150000
               1999      150000
               2000      144000
               2001      234000
               2002      162000
               2003      240000
               2005      250000
               2006      280000
               2007      244000
               2008      156000
               2009      175000
               2010       67000
               2011       12000
               2012       41000
               2013       17000
               2014       56000
               2015       55000
               2016       48000
               2017       42000
               2018       34000
               2019       44000
               2020       58000
               2021       73000
Louisiana      1995     3927000
               1996     3922000
               1997     4370000
               1998     4551000
               1999     5472000
               2000     4042000
               2001     4770000
               2002     4340000
               2003     3060000
               2004     3430000
               2005     3395000
               2006     2700000
               2007     2581000
               2008     2233000
               2009     3811000
               2010      288000
               2011      471000
               2012      141000
               2013      490000
               2014      524000
               2015      348000
               2016      301000
               2017      279000
               2018      261000
               2019      428000
               2020      228000
               2021      205000
Maine          1995      495000
               1996      230000
               1997      152000
               1998      260000
               1999      308000
               2000      231000
               2001      220000
               2002      451000
               2003      264000
               2004      217000
               2005      208000
               2006      253000
               2007      234000
               2008      294000
               2009      300000
               2010       33000
               2011       17000
               2012       24000
               2013       27000
               2014       41000
               2015       47000
               2016       65000
               2017       51000
               2018       92000
               2019      110000
               2020       78000
               2021       60000
Maryland       1995      245000
               1996      224000
               1997      240000
               1998      308000
               1999      276000
               2000      276000
               2001      184000
               2002      138000
               2003       84000
Michigan       1995     8924000
               1996     8640000
               1997     5950000
               1998     6800000
               1999     6205000
               2000     5400000
               2001     4560000
               2002     5544000
               2003     4810000
               2004     4355000
               2005     4420000
               2006     3960000
               2007     4608000
               2008     5183000
               2009     3960000
               2010     1524000
               2011     2084000
               2012     1332000
               2013      982000
               2014     1835000
               2015     1984000
               2016     1709000
               2017      822000
               2018      768000
               2019     1363000
               2020     1384000
               2021     1957000
Minnesota      1995    13530000
               1996    11550000
               1997    10585000
               1998    11060000
               1999    11890000
               2000    13500000
               2001    10935000
               2002     8541000
               2003     9960000
               2004    10125000
               2005     8880000
               2006    10000000
               2007     8840000
               2008     9516000
               2009     7930000
               2010     1774000
               2011     2099000
               2012     1591000
               2013     1282000
               2014     1426000
               2015     2157000
               2016     1390000
               2017     1016000
               2018     1161000
               2019     3063000
               2020     2495000
               2021      285000
Mississippi    1995     1120000
               1996     1360000
               1997     1387000
               1998     1548000
               1999     1314000
               2000     1224000
               2001     1122000
               2002     1404000
               2003     1449000
               2004     1170000
               2005     1280000
               2006     1372000
               2007     1575000
               2008     1372000
               2009     1456000
               2010       78000
               2011      104000
               2012       64000
               2013       39000
               2014       45000
               2015       87000
               2016      113000
               2017      124000
               2018       70000
               2019      141000
               2020      146000
               2021       71000
Missouri       1995     1541000
               1996     1628000
               1997     1848000
               1998     1518000
               1999     1560000
               2000     1725000
               2001     1525000
               2002      954000
               2003      901000
               2004      656000
               2005      750000
               2006      690000
               2007      611000
               2008      583000
               2009      517000
               2010       92000
               2011       76000
               2012      108000
               2013       85000
               2014       96000
               2015       52000
               2016       30000
               2017       57000
               2018       36000
               2019       73000
               2020      100000
               2021       92000
Montana        1995     8480000
               1996     7020000
               1997    12840000
               1998    14030000
               1999     8540000
               2000    12728000
               2001    13872000
               2002     8442000
               2003     9570000
               2004    10780000
               2005     8710000
               2006    10428000
               2007     9180000
               2008     9380000
               2009    10220000
               2010     2905000
               2011     3202000
               2012     2413000
               2013     5231000
               2014     5132000
               2015     3757000
               2016     3183000
               2017     2506000
               2018     3680000
               2019     5802000
               2020     3208000
               2021     1934000
Nebraska       1995     4380000
               1996     4875000
               1997     4087000
               1998     4480000
               1999     4466000
               2000     4350000
               2001     2064000
               2002     3225000
               2003     3330000
               2004     4539000
               2005     2720000
               2006     3431000
               2007     2205000
               2008     2412000
               2009     2688000
               2010      902000
               2011      653000
               2012     1146000
               2013     1628000
               2014     1688000
               2015     1450000
               2016      640000
               2017      423000
               2018      850000
               2019      223000
               2020      250000
               2021      550000
Nevada         1995      261000
               1996      854000
               1997      854000
               1998      460000
               1999      383000
               2000      350000
               2001      550000
               2002      558000
               2003      384000
               2004      770000
               2005      552000
               2006      333000
               2007      280000
               2008      290000
               2009      520000
NewJersey      1995      272000
               1996      225000
               1997      392000
               1998      539000
               1999      440000
               2000      385000
               2001      374000

In [27]:
df.groupby('state').filter(lambda x: x['production'].sum() > 1000000)

,Unnamed: 0,state,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
0,0,Alabama,16000,58,928000,28000,62.00,575000,1995
1,1,Arizona,52000,79,4108000,986000,68.00,2793000,1995
2,2,Arkansas,50000,60,3000000,900000,64.00,1920000,1995
3,3,California,420000,93,39060000,4687000,60.00,23436000,1995
4,4,Colorado,45000,60,2700000,1404000,68.00,1836000,1995
5,5,Florida,230000,86,19780000,1780000,63.00,12461000,1995
6,6,Georgia,70000,62,4340000,260000,69.00,2995000,1995
7,7,Hawaii,8000,129,1032000,103000,55.00,568000,1995
8,8,Idaho,125000,48,6000000,1020000,65.00,3900000,1995
9,9,Illinois,11000,74,814000,212000,102.00,830000,1995
10,10,Indiana,12000,63,756000,166000,68.00,514000,1995
11,11,Iowa,50000,68,3400000,612000,72.00,2448000,1995
12,12,Kansas,17000,67,1139000,182000,71.00,809000,1995
13,13,Kentucky,3000,44,132000,30000,103.00,136000,1995
14,14,Louisiana,33000,119,3927000,275000,61.00,2395000,1995
15,15,Maine,11000,45,495000,223000,100.00,495000,1995
16,16,Maryland,7000,35,245000,81000,114.00,279000,1995
17,17,Michigan,97000,92,8924000,3570000,72.00,6425000,1995
18,18,Minnesota,165000,82,13530000,1218000,66.00,8930000,1995
19,19,Mississippi,16000,70,1120000,146000,64.00,717000,1995
20,20,Missouri,23000,67,1541000,308000,65.00,1002000,1995
21,21,Montana,106000,80,8480000,1781000,66.00,5597000,1995
22,22,Nebraska,60000,73,4380000,1402000,68.00,2978000,1995
23,23,Nevada,9000,29,261000,34000,96.00,251000,1995
24,24,NewJersey,8000,34,272000,57000,71.00,193000,1995
25,25,NewMexico,19000,65,1235000,247000,68.00,840000,1995
26,26,NewYork,70000,75,5250000,2100000,66.00,3465000,1995
27,27,NorthCarolina,12000,52,624000,162000,81.00,505000,1995
28,28,NorthDakota,220000,108,23760000,3802000,63.00,14969000,1995
29,29,Ohio,25000,62,1550000,930000,72.00,1116000,1995
30,30,Oklahoma,5000,76,380000,141000,91.00,346000,1995
31,31,Oregon,52000,52,2704000,2488000,71.00,1920000,1995
32,32,Pennsylvania,25000,43,1075000,376000,69.00,742000,1995
33,33,SouthCarolina,9000,90,810000,65000,128.00,1037000,1995
34,34,SouthDakota,240000,85,20400000,4896000,65.00,13260000,1995
35,35,Tennessee,4000,53,212000,70000,114.00,242000,1995
36,36,Texas,84000,106,8904000,1959000,64.00,5699000,1995
37,37,Utah,32000,33,1056000,232000,61.00,644000,1995
38,38,Vermont,5000,67,335000,131000,83.00,278000,1995
39,39,Virginia,9000,45,405000,97000,55.00,223000,1995
40,40,Washington,60000,59,3540000,637000,54.00,1912000,1995
41,41,WestVirginia,13000,41,533000,48000,116.00,618000,1995
42,42,Wisconsin,73000,79,5767000,2134000,71.00,4095000,1995
43,43,Wyoming,38000,36,1368000,150000,68.00,930000,1995
44,44,Alabama,16000,64,1024000,102000,86.00,881000,1996
45,45,Arizona,32000,60,1920000,307000,84.00,1613000,1996
46,46,Arkansas,40000,84,3360000,336000,87.00,2923000,1996
47,47,California,390000,70,27300000,4641000,84.00,22932000,1996
48,48,Colorado,30000,74,2220000,1132000,79.00,1754000,1996
49,49,Florida,240000,105,25200000,2268000,91.00,22932000,1996
50,50,Georgia,75000,68,5100000,306000,89.00,4539000,1996
51,51,Hawaii,8000,155,1240000,62000,80.00,992000,1996
52,52,Idaho,110000,45,4950000,1535000,90.00,4455000,1996
53,53,Illinois,11000,74,814000,285000,130.00,1058000,1996
54,54,Indiana,9000,75,675000,412000,107.00,722000,1996
55,55,Iowa,58000,67,3886000,933000,98.00,3808000,1996
56,56,Kansas,16000,51,816000,294000,96.00,783000,1996
57,57,Kentucky,3000,60,180000,23000,127.00,229000,1996
58,58,Louisiana,37000,106,3922000,784000,84.00,3294000,1996
59,59,Maine,10000,23,230000,23000,126.00,290000,1996
60,60,Maryland,7000,32,224000,40000,111.00,249000,1996
61,61,Michigan,90000,96,8640000,4320000,110.00,9504000,1996
62,62,Minnesota,150000,77,11550000,1617000,91.00,10511000,1996
63,63,Mississippi,17000,80,1360000,299000,85.00,1156000,1996
64,64,Missouri,22000,74,1628000,326000,92.00,1498000,1996
65,65,Montana,117000,60,7020000,1825000,88.00,6178000,1996
66,66,Nebraska,65000,75,4875000,1755000,92.00,4485000,1996
67,67,Nevada,14000,61,854000,68000,105.00,897000,1996
68,68,NewJersey,5000,45,225000,119000,106.00,239000,1996
69,69,NewMexico,15000,77,1155000,219000,94.00,1086000,1996
70,70,NewYork,68000,80,5440000,2557000,88.00,4787000,1996
71,71,NorthCarolina,12000,44,528000,53000,106.00,560000,1996
72,72,NorthDakota,230000,86,19780000,4945000,90.00,17802000,1996
73,73,Ohio,24000,70,1680000,840000,98.00,1646000,1996
74,74,Oklahoma,4000,59,236000,54000,107.00,253000,1996
75,75,Oregon,55000,59,3245000,1071000,92.00,2985000,1996
76,76,Pennsylvania,23000,46,1058000,370000,99.00,1047000,1996
77,77,SouthCarolina,9000,90,810000,81000,113.00,915000,1996
78,78,SouthDakota,240000,97,23280000,6751000,91.00,21185000,1996
79,79,Tennessee,5000,64,320000,90000,137.00,438000,1996
80,80,Texas,82000,83,6806000,1361000,87.00,5921000,1996
81,81,Utah,34000,46,1564000,328000,85.00,1329000,1996
82,82,Vermont,4000,83,332000,93000,108.00,359000,1996
83,83,Virginia,7000,50,350000,119000,136.00,476000,1996
84,84,Washington,57000,58,3306000,1025000,89.00,2942000,1996
85,85,WestVirginia,10000,59,590000,207000,169.00,997000,1996
86,86,Wisconsin,69000,78,5382000,2422000,83.00,4467000,1996
87,87,Wyoming,40000,73,2920000,526000,91.00,2657000,1996
88,88,Alabama,14000,66,924000,92000,81.00,748000,1997
89,89,Arizona,32000,80,2560000,1024000,72.00,1843000,1997
90,90,Arkansas,40000,95,3800000,2774000,70.00,2660000,1997
91,91,California,400000,75,30000000,9000000,70.00,21000000,1997
92,92,Colorado,35000,55,1925000,982000,82.00,1579000,1997
93,93,Florida,240000,67,16080000,2734000,73.00,11738000,1997
94,94,Georgia,75000,46,3450000,587000,79.00,2726000,1997
95,95,Hawaii,9000,146,1314000,158000,86.00,1130000,1997
96,96,Idaho,120000,64,7680000,2304000,72.00,5530000,1997
97,97,Illinois,7000,69,483000,222000,127.00,613000,1997
98,98,Indiana,8000,71,568000,352000,113.00,642000,1997
99,99,Iowa,51000,74,3774000,2000000,86.00,3246000,1997
100,100,Kansas,17000,71,1207000,688000,81.00,978000,1997
101,101,Kentucky,3000,60,180000,54000,148.00,266000,1997
102,102,Louisiana,38000,115,4370000,656000,70.00,3059000,1997
103,103,Maine,8000,19,152000,9000,70.00,106000,1997
104,104,Maryland,6000,40,240000,65000,159.00,382000,1997
105,105,Michigan,85000,70,5950000,3273000,77.00,4582000,1997
106,106,Minnesota,145000,73,10585000,2011000,74.00,7833000,1997
107,107,Mississippi,19000,73,1387000,777000,73.00,1013000,1997
108,108,Missouri,24000,77,1848000,517000,78.00,1441000,1997
109,109,Montana,107000,120,12840000,4237000,74.00,9502000,1997
110,110,Nebraska,61000,67,4087000,2738000,77.00,3147000,1997
111,111,Nevada,14000,61,854000,171000,114.00,974000,1997
112,112,NewJersey,8000,49,392000,161000,104.00,408000,1997
113,113,NewMexico,15000,60,900000,396000,87.00,783000,1997
114,114,NewYork,72000,60,4320000,2246000,85.00,3672000,1997
115,115,NorthCarolina,8000,58,464000,139000,119.00,552000,1997
116,116,NorthDakota,245000,100,24500000,7350000,74.00,18130000,1997
117,117,Ohio,22000,80,1760000,827000,85.00,1496000,1997
118,118,Oklahoma,4000,58,232000,97000,137.00,318000,1997
119,119,Oregon,47000,53,2491000,1445000,79.00,1968000,1997
120,120,Pennsylvania,22000,48,1056000,528000,100.00,1056000,1997
121,121,SouthDakota,240000,65,15600000,8736000,74.00,11544000,1997
122,122,Tennessee,6000,62,372000,126000,147.00,547000,1997
123,123,Texas,94000,106,9964000,3188000,75.00,7473000,1997
124,124,Utah,32000,52,1664000,699000,75.00,1248000,1997
125,125,Vermont,5000,63,315000,249000,83.00,261000,1997
126,126,Virginia,8000,53,424000,157000,145.00,615000,1997
127,127,Washington,54000,52,2808000,1348000,76.00,2134000,1997
128,128,WestVirginia,8000,70,560000,280000,111.00,622000,1997
129,129,Wisconsin,79000,60,4740000,2797000,90.00,4266000,1997
130,130,Wyoming,38000,62,2356000,660000,75.00,1767000,1997
131,131,Alabama,16000,71,1136000,159000,72.00,818000,1998
132,132,Arizona,55000,60,3300000,1485000,64.00,2112000,1998
133,133,Arkansas,53000,65,3445000,1688000,59.00,2033000,1998
134,134,California,450000,83,37350000,12326000,62.00,23157000,1998
135,135,Colorado,27000,72,1944000,1594000,70.00,1361000,1998
136,136,Florida,230000,98,22540000,4508000,64.00,14426000,1998
137,137,Georgia,75000,56,4200000,307000,69.00,2898000,1998
138,138,Hawaii,8000,118,944000,66000,75.00,708000,1998
139,139,Idaho,120000,50,6000000,2220000,65.00,3900000,1998
140,140,Illinois,9000,71,639000,204000,119.00,760000,1998
141,141,Indiana,9000,92,828000,489000,85.00,704000,1998
142,142,Iowa,50000,78,3900000,2301000,70.00,2730000,1998
143,143,Kansas,16000,46,736000,390000,87.00,640000,1998
144,144,Kentucky,3000,50,150000,51000,140.00,210000,1998
145,145,Louisiana,41000,111,4551000,865000,59.00,2685000,1998
146,146,Maine,10000,26,260000,117000,69.00,179000,1998
147,147,Maryland,7000,44,308000,92000,110.00,339000,1998
148,148,Michigan,80000,85,6800000,3672000,66.00,4488000,1998
149,149,Minnesota,140000,79,11060000,2765000,65.00,7189000,1998
150,150,Mississippi,18000,86,1548000,898000,58.00,898000,1998
151,151,Missouri,23000,66,1518000,455000,76.00,1154000,1998
152,152,Montana,115000,122,14030000,5472000,64.00,8979000,1998
153,153,Nebraska,64000,70,4480000,2240000,86.00,3853000,1998
154,154,Nevada,10000,46,460000,175000,165.00,759000,1998
155,155,NewJersey,11000,49,539000,167000,76.00,410000,1998
156,156,NewMexico,14000,55,770000,470000,76.00,585000,1998
157,157,NewYork,65000,80,5200000,2444000,70.00,3640000,1998
158,158,NorthCarolina,8000,59,472000,151000,138.00,651000,1998
159,159,NorthDakota,230000,128,29440000,8832000,63.00,18547000,1998
160,160,Ohio,18000,78,1404000,702000,83.00,1165000,1998
161,161,Oklahoma,4000,51,204000,63000,124.00,253000,1998
162,162,Oregon,50000,45,2250000,1620000,90.00,2025000,1998
163,163,Pennsylvania,23000,66,1518000,698000,80.00,1214000,1998
164,164,SouthDakota,225000,95,21375000,10901000,64.00,13680000,1998
165,165,Tennessee,7000,64,448000,121000,132.00,591000,1998
166,166,Texas,91000,77,7007000,1612000,62.00,4344000,1998
167,167,Utah,30000,58,1740000,557000,65.00,1131000,1998
168,168,Vermont,6000,64,384000,207000,107.00,411000,1998
169,169,Virginia,8000,37,296000,86000,133.00,394000,1998
170,170,Washington,58000,51,2958000,1361000,64.00,1893000,1998
171,171,WestVirginia,6000,55,330000,155000,114.00,376000,1998
172,172,Wisconsin,89000,91,8099000,5264000,72.00,5831000,1998
173,173,Wyoming,46000,60,2760000,524000,68.00,1877000,1998
174,174,Alabama,17000,68,1156000,185000,56.00,647000,1999
175,175,Arizona,52000,62,3224000,1548000,62.00,1999000,1999
176,176,Arkansas,52000,89,4628000,2592000,53.00,2453000,1999
177,177,California,505000,60,30300000,10302000,53.00,16059000,1999
178,178,Colorado,27000,76,2052000,1436000,68.00,1395000,1999
179,179,Florida,228000,102,23256000,4186000,53.00,12326000,1999
180,180,Georgia,65000,51,3315000,497000,64.00,2122000,1999
181,181,Hawaii,8000,80,640000,32000,78.00,499000,1999
182,182,Idaho,120000,48,5760000,3110000,59.00,3398000,1999
183,183,Illinois,9000,66,594000,327000,115.00,683000,1999
184,184,Indiana,10000,81,810000,437000,90.00,729000,1999
185,185,Iowa,40000,65,2600000,2028000,65.00,1690000,1999
186,186,Kansas,13000,67,871000,854000,111.00,967000,1999
187,187,Kentucky,3000,50,150000,12000,124.00,186000,1999
188,188,Louisiana,48000,114,5472000,821000,49.00,2681000,1999
189,189,Maine,14000,22,308000,89000,83.00,256000,1999
190,190,Maryland,6000,46,276000,50000,164.00,453000,1999
191,191,Michigan,73000,85,6205000,3475000,66.00,4095000,1999
192,192,Minnesota,145000,82,11890000,3210000,61.00,7253000,1999
193,193,Mississippi,18000,73,1314000,591000,54.00,710000,1999
194,194,Missouri,24000,65,1560000,437000,68.00,1061000,1999
195,195,Montana,122000,70,8540000,2135000,60.00,5124000,1999
196,196,Nebraska,58000,77,4466000,1965000,61.00,2724000,1999
197,197,Nevada,9000,45,383000,257000,154.00,590000,1999
198,198,NewJersey,10000,44,440000,154000,57.00,251000,1999
199,199,NewMexico,15000,52,780000,476000,77.00,601000,1999
200,200,NewYork,69000,70,4830000,2077000,66.00,3188000,1999
201,201,NorthCarolina,9000,46,414000,104000,162.00,671000,1999
202,202,NorthDakota,255000,105,26775000,8836000,59.00,15797000,1999
203,203,Ohio,20000,74,1480000,784000,72.00,1066000,1999
204,204,Oklahoma,6000,45,270000,49000,134.00,362000,1999
205,205,Oregon,45000,57,2565000,2026000,80.00,2052000,1999
206,206,Pennsylvania,25000,60,1500000,705000,76.00,1140000,1999
207,207,SouthDakota,224000,104,23296000,13046000,60.00,13978000,1999
208,208,Tennessee,8000,51,408000,106000,130.00,530000,1999
209,209,Texas,108000,81,8748000,2799000,64.00,5599000,1999
210,210,Utah,26000,45,1170000,433000,68.00,796000,1999
211,211,Vermont,6000,66,396000,222000,63.00,249000,1999
212,212,Virginia,7000,35,245000,86000,117.00,287000,1999
213,213,Washington,52000,50,2600000,1170000,60.00,1560000,1999
214,214,WestVirginia,6000,39,234000,152000,109.00,255000,1999
215,215,Wisconsin,80000,75,6000000,4560000,68.00,4080000,1999
216,216,Wyoming,37000,72,2664000,746000,61.00,1625000,1999
217,217,Alabama,16000,78,1248000,187000,59.00,736000,2000
218,218,Arizona,40000,59,2360000,1322000,73.00,1723000,2000
219,219,Arkansas,55000,93,5115000,3529000,57.00,2916000,2000
220,220,California,440000,70,30800000,11396000,58.00,17864000,2000
221,221,Colorado,29000,60,1740000,957000,62.00,1079000,2000
222,222,Florida,232000,105,24360000,2923000,54.00,13154000,2000
223,223,Georgia,55000,57,3135000,376000,63.00,1975000,2000
224,224,Hawaii,7000,112,784000,125000,81.00,635000,2000
225,225,Idaho,100000,47,4700000,2679000,52.00,2444000,2000
226,226,Illinois,8000,61,488000,146000,117.00,571000,2000
227,227,Indiana,8000,65,520000,286000,103.00,536000,2000
228,228,Iowa,30000,67,2010000,1206000,67.00,1347000,2000
229,229,Kansas,15000,68,1020000,520000,91.00,928000,2000
230,230,Kentucky,3000,48,144000,40000,135.00,194000,2000
231,231,Louisiana,43000,94,4042000,1334000,52.00,2102000,2000
232,232,Maine,11000,21,231000,143000,75.00,173000,2000
233,233,Maryland,6000,46,276000,52000,114.00,315000,2000
234,234,Michigan,72000,75,5400000,2970000,60.00,3240000,2000
235,235,Minnesota,150000,90,13500000,3105000,57.00,7695000,2000
236,236,Mississippi,17000,72,1224000,649000,69.00,845000,2000
237,237,Missouri,23000,75,1725000,362000,60.00,1035000,2000
238,238,Montana,148000,86,12728000,5982000,59.00,7510000,2000
239,239,Nebraska,50000,87,4350000,2610000,59.00,2567000,2000
240,240,Nevada,10000,35,350000,95000,145.00,508000,2000
241,241,NewJersey,11000,35,385000,200000,61.00,235000,2000
242,242,NewMexico,15000,64,960000,739000,72.00,691000,2000
243,243,NewYork,58000,80,4640000,2274000,55.00,2552000,2000
244,244,NorthCarolina,11000,49,539000,243000,143.00,771000,2000
245,245,NorthDakota,290000,115,33350000,13340000,56.00,18676000,2000
246,246,Ohio,18000,65,1170000,585000,79.00,924000,2000
247,247,Oklahoma,7000,35,245000,64000,126.00,309000,2000
248,248,Oregon,48000,51,2448000,1665000,66.00,1616000,2000
249,249,Pennsylvania,22000,45,990000,554000,76.00,752000,2000
250,250,SouthDakota,235000,121,28435000,12796000,57.00,16208000,2000
251,251,Tennessee,9000,61,549000,104000,143.00,785000,2000
252,252,Texas,105000,79,8295000,2986000,57.00,4728000,2000
253,253,Utah,24000,41,984000,462000,60.00,590000,2000
254,254,Vermont,7000,59,413000,211000,68.00,281000,2000
255,255,Virginia,7000,42,294000,103000,150.00,441000,2000
256,256,Washington,52000,54,2808000,1151000,58.00,1629000,2000
257,257,WestVirginia,7000,54,378000,234000,122.00,461000,2000
258,258,Wisconsin,84000,90,7560000,4385000,68.00,5141000,2000
259,259,Wyoming,39000,93,3627000,798000,59.00,2140000,2000
260,260,Alabama,14000,73,1022000,235000,71.00,726000,2001
261,261,Arizona,43000,59,2537000,1142000,78.00,1979000,2001
262,262,Arkansas,58000,98,5655000,1872000,66.00,3732000,2001
263,263,California,425000,65,27625000,7735000,67.00,18509000,2001
264,264,Colorado,26000,55,1430000,529000,70.00,1001000,2001
265,265,Florida,220000,100,22000000,3432000,62.00,13640000,2001
266,266,Georgia,55000,57,3135000,188000,70.00,2195000,2001
267,267,Hawaii,8000,87,696000,84000,85.00,592000,2001
268,268,Idaho,100000,46,4600000,1610000,66.00,3036000,2001
269,269,Illinois,6000,76,456000,251000,172.00,784000,2001
270,270,Indiana,8000,76,608000,213000,86.00,523000,2001
271,271,Iowa,33000,51,1683000,875000,73.00,1229000,2001
272,272,Kansas,13000,51,663000,530000,85.00,564000,2001
273,273,Kentucky,3000,78,234000,94000,131.00,307000,2001
274,274,Louisiana,45000,106,4770000,572000,60.00,2862000,2001
275,275,Maine,11000,20,220000,106000,70.00,154000,2001
276,276,Maryland,4000,46,184000,55000,172.00,316000,2001
277,277,Michigan,76000,60,4560000,2827000,78.00,3557000,2001
278,278,Minnesota,135000,81,10935000,1859000,63.00,6889000,2001
279,279,Mississippi,17000,66,1122000,224000,60.00,673000,2001
280,280,Missouri,25000,61,1525000,381000,68.00,1037000,2001
281,281,Montana,136000,102,13872000,4578000,65.00,9017000,2001
282,282,Nebraska,43000,48,2064000,1115000,66.00,1362000,2001
283,283,Nevada,11000,50,550000,44000,201.00,1106000,2001
284,284,NewJersey,11000,34,374000,71000,82.00,307000,2001
285,285,NewMexico,15000,70,1050000,525000,65.00,683000,2001
286,286,NewYork,53000,70,3710000,1781000,68.00,2523000,2001
287,287,NorthCarolina,11000,44,484000,145000,158.00,765000,2001
288,288,NorthDakota,280000,96,26880000,9408000,65.00,17472000,2001
289,289,Ohio,16000,81,1296000,505000,85.00,1102000,2001
290,290,Oklahoma,4000,47,188000,105000,141.00,265000,2001
291,291,Oregon,44000,44,1936000,1200000,69.00,1336000,2001
292,292,Pennsylvania,17000,57,969000,514000,87.00,843000,2001
293,293,SouthDakota,235000,65,15275000,12220000,64.00,9776000,2001
294,294,Tennessee,9000,59,531000,147000,137.00,727000,2001
295,295,Texas,97000,79,7663000,1533000,64.00,4904000,2001
296,296,Utah,23000,38,874000,315000,65.00,568000,2001
297,297,Vermont,7000,81,567000,249000,91.00,516000,2001
298,298,Virginia,9000,52,468000,94000,117.00,548000,2001
299,299,Washington,42000,52,2184000,917000,67.00,1463000,2001
300,300,WestVirginia,7000,65,455000,410000,155.00,705000,2001
301,301,Wisconsin,67000,81,5427000,3419000,76.00,4125000,2001
302,302,Wyoming,38000,77,2926000,468000,63.00,1843000,2001
303,303,Alabama,12000,86,1032000,103000,111.00,1146000,2002
304,304,Arizona,38000,63,2394000,1197000,110.00,2633000,2002
305,305,Arkansas,55000,88,4840000,1065000,124.00,6002000,2002
306,306,California,440000,53,23320000,3498000,129.00,30083000,2002
307,307,Colorado,24000,60,1440000,576000,122.00,1757000,2002
308,308,Florida,220000,93,20460000,2026000,112.00,22915000,2002
309,309,Georgia,50000,52,2600000,52000,110.00,2860000,2002
310,310,Hawaii,7000,136,952000,29000,110.00,1047000,2002
311,311,Idaho,100000,57,5700000,1653000,135.00,7695000,2002
312,312,Illinois,9000,80,720000,130000,142.00,1022000,2002
313,313,Indiana,8000,62,496000,233000,114.00,565000,2002
314,314,Iowa,33000,70,2310000,901000,137.00,3165000,2002
315,315,Kansas,17000,52,884000,407000,156.00,1379000,2002
316,316,Kentucky,3000,54,162000,47000,165.00,267000,2002
317,317,Louisiana,35000,124,4340000,347000,114.00,4948000,2002
318,318,Maine,11000,41,451000,266000,121.00,546000,2002
319,319,Maryland,3000,46,138000,21000,175.00,242000,2002
320,320,Michigan,72000,77,5544000,1885000,134.00,7429000,2002
321,321,Minnesota,117000,73,8541000,1110000,142.00,12128000,2002
322,322,Mississippi,18000,78,1404000,281000,118.00,1657000,2002
323,323,Missouri,18000,53,954000,200000,137.00,1307000,2002
324,324,Montana,134000,63,8442000,1097000,135.00,11397000,2002
325,325,Nebraska,43000,75,3225000,1161000,145.00,4676000,2002
326,326,Nevada,9000,62,558000,61000,227.00,1267000,2002
327,327,NewJersey,10000,35,350000,74000,98.00,343000,2002
328,328,NewMexico,11000,44,484000,252000,109.00,528000,2002
329,329,NewYork,60000,98,5880000,2470000,117.00,6880000,2002
330,330,NorthCarolina,14000,51,714000,86000,136.00,971000,2002
331,331,NorthDakota,320000,75,24000000,8160000,142.00,34080000,2002
332,332,Ohio,16000,81,1296000,518000,140.00,1814000,2002
333,333,Oklahoma,3000,53,159000,51000,160.00,254000,2002
334,334,Oregon,39000,49,1911000,803000,128.00,2446000,2002

In [28]:
df.groupby(['state','year']).agg(
Total_Production=('production','sum'),
Avg_Price=('average_price','mean'),
Revenue=('value_of_production','sum')
).reset_index()

              state  year  Total_Production  Avg_Price   Revenue
0           Alabama  1995            928000      62.00    575000
1           Alabama  1996           1024000      86.00    881000
2           Alabama  1997            924000      81.00    748000
3           Alabama  1998           1136000      72.00    818000
4           Alabama  1999           1156000      56.00    647000
5           Alabama  2000           1248000      59.00    736000
6           Alabama  2001           1022000      71.00    726000
7           Alabama  2002           1032000     111.00   1146000
8           Alabama  2003           1066000     126.00   1343000
9           Alabama  2004           1044000     140.00   1462000
10          Alabama  2005            858000     128.00   1098000
11          Alabama  2006            792000     146.00   1156000
12          Alabama  2007            616000     141.00    869000
13          Alabama  2008            594000     186.00   1105000
14          Alabama  2009            441000     182.00    803000
15          Alabama  2010             73000     240.00   1166000
16          Alabama  2011             63000     251.00   1130000
17          Alabama  2012             65000     247.00   1067000
18          Alabama  2013             55000     285.00   1037000
19          Alabama  2014             26000     353.00   1310000
20          Alabama  2015             13000     383.00   1260000
21          Alabama  2016             33000     345.00   1256000
22          Alabama  2017             22000     288.00    907000
23          Alabama  2018             14000       3.72   1004000
24          Alabama  2019             44000       3.38    994000
25          Alabama  2020             66000       5.52   1507000
26          Alabama  2021            112000       5.99   1917000
27          Arizona  1995           4108000      68.00   2793000
28          Arizona  1996           1920000      84.00   1613000
29          Arizona  1997           2560000      72.00   1843000
30          Arizona  1998           3300000      64.00   2112000
31          Arizona  1999           3224000      62.00   1999000
32          Arizona  2000           2360000      73.00   1723000
33          Arizona  2001           2537000      78.00   1979000
34          Arizona  2002           2394000     110.00   2633000
35          Arizona  2003           2880000     138.00   3974000
36          Arizona  2004           1760000     115.00   2024000
37          Arizona  2005           1800000      97.00   1746000
38          Arizona  2006           1950000     139.00   2711000
39          Arizona  2007           1920000     118.00   2266000
40          Arizona  2008           1600000     125.00   2000000
41          Arizona  2009           1040000     153.00   1591000
42          Arizona  2010            665000     152.00   2809000
43          Arizona  2011            427000     155.00   1889000
44          Arizona  2012            253000     179.00   1811000
45          Arizona  2013            251000     196.00   2046000
46          Arizona  2014            193000     192.00   1947000
47          Arizona  2015            306000     203.00   2586000
48          Arizona  2016            261000     197.00   2447000
49          Arizona  2017             97000     199.00   1751000
50          Arizona  2018            109000       3.01   2745000
51          Arizona  2019            201000       2.04   2158000
52          Arizona  2020            360000       2.38   2142000
53          Arizona  2021            368000       2.34   2434000
54         Arkansas  1995           3000000      64.00   1920000
55         Arkansas  1996           3360000      87.00   2923000
56         Arkansas  1997           3800000      70.00   2660000
57         Arkansas  1998           3445000      59.00   2033000
58         Arkansas  1999           4628000      53.00   2453000
59         Arkansas  2000           5115000      57.00   2916000
60         Arkansas  2001           5655000      66.00   3732000
61         Arkansas  2002           4840000     124.00   6002000
62         Arkansas  2003           3000000     127.00   3810000
63         Arkansas  2004           2280000      90.00   2052000
64         Arkansas  2005           2484000      95.00   2360000
65         Arkansas  2006           2432000     105.00   2554000
66         Arkansas  2007           2240000      95.00   2128000
67         Arkansas  2008           2100000     131.00   2751000
68         Arkansas  2009           1368000     139.00   1902000
69         Arkansas  2010            360000     147.00   2205000
70         Arkansas  2011            239000     162.00   2281000
71         Arkansas  2012            189000     198.00   3119000
72         Arkansas  2013             66000     202.00   2666000
73         Arkansas  2014            137000     204.00   2785000
74         Arkansas  2015            121000     206.00   3560000
75         Arkansas  2016             99000     185.00   3064000
76         Arkansas  2017            197000     197.00   3885000
77         Arkansas  2018             84000       1.88   2632000
78         Arkansas  2019            176000       1.65   1815000
79         Arkansas  2020            176000       1.85   1813000
80         Arkansas  2021            255000       2.07   1760000
81       California  1995          39060000      60.00  23436000
82       California  1996          27300000      84.00  22932000
83       California  1997          30000000      70.00  21000000
84       California  1998          37350000      62.00  23157000
85       California  1999          30300000      53.00  16059000
86       California  2000          30800000      58.00  17864000
87       California  2001          27625000      67.00  18509000
88       California  2002          23320000     129.00  30083000
89       California  2003          32160000     142.00  45667000
90       California  2004          17550000     101.00  17726000
91       California  2005          30000000      84.00  25200000
92       California  2006          19760000      98.00  19365000
93       California  2007          13600000     104.00  14144000
94       California  2008          18360000     141.00  25888000
95       California  2009          11715000     139.00  16284000
96       California  2010           6318000     155.00  42579000
97       California  2011           3730000     165.00  29304000
98       California  2012           3119000     194.00  22407000
99       California  2013           2505000     211.00  22978000
100      California  2014           2995000     206.00  25709000
101      California  2015           1485000     203.00  16748000
102      California  2016           2009000     204.00  22766000
103      California  2017           2198000     216.00  29668000
104      California  2018           3022000       2.11  28981000
105      California  2019           3216000       1.60  25728000
106      California  2020           2752000       1.95  26832000
107      California  2021           1627000       2.40  22968000
108        Colorado  1995           2700000      68.00   1836000
109        Colorado  1996           2220000      79.00   1754000
110        Colorado  1997           1925000      82.00   1579000
111        Colorado  1998           1944000      70.00   1361000
112        Colorado  1999           2052000      68.00   1395000
113        Colorado  2000           1740000      62.00   1079000
114        Colorado  2001           1430000      70.00   1001000
115        Colorado  2002           1440000     122.00   1757000
116        Colorado  2003           2064000     138.00   2848000
117        Colorado  2004           1840000     148.00   2723000
118        Colorado  2005           1820000     104.00   1893000
119        Colorado  2006           2700000     139.00   3753000
120        Colorado  2007           1683000     112.00   1885000
121        Colorado  2008           1215000     150.00   1823000
122        Colorado  2009           1484000     140.00   2078000
123        Colorado  2010            533000     152.00   2894000
124        Colorado  2011            443000     200.00   3410000
125        Colorado  2012            468000     207.00   2484000
126        Colorado  2013            324000     210.00   2348000
127        Colorado  2014            200000     211.00   2108000
128        Colorado  2015            399000     226.00   3343000
129        Colorado  2016            282000     224.00   2867000
130        Colorado  2017            284000     209.00   2966000
131        Colorado  2018            283000       2.05   3050000
132        Colorado  2019            500000       2.34   3444000
133        Colorado  2020            455000       2.39   2940000
134        Colorado  2021            232000       2.78   3225000
135         Florida  1995          19780000      63.00  12461000
136         Florida  1996          25200000      91.00  22932000
137         Florida  1997          16080000      73.00  11738000
138         Florida  1998          22540000      64.00  14426000
139         Florida  1999          23256000      53.00  12326000
140         Florida  2000          24360000      54.00  13154000
141         Florida  2001          22000000      62.00  13640000
142         Florida  2002          20460000     112.00  22915000
143         Florida  2003          14910000     135.00  20129000
144         Florida  2004          20090000     100.00  20090000
145         Florida  2005          13760000      87.00  11971000
146         Florida  2006          13770000     101.00  13908000
147         Florida  2007          11360000      99.00  11246000
148         Florida  2008          11850000     130.00  15405000
149         Florida  2009          10200000     138.00  14076000
150         Florida  2010           1794000     156.00  21528000
151         Florida  2011            988000     168.00  18446000
152         Florida  2012           1235000     184.00  22728000
153         Florida  2013           1074000     203.00  27243000
154         Florida  2014           1029000     208.00  30576000
155         Florida  2015            832000     197.00  23404000
156         Florida  2016            538000     243.00  26123000
157         Florida  2017            529000     237.00  20892000
158         Florida  2018            737000       2.40  25284000
159         Florida  2019            830000       2.46  22694000
160         Florida  2020            883000       2.24  19784000
161         Florida  2021            849000       2.42  20551000
162         Georgia  1995           4340000      69.00   2995000
163         Georgia  1996           5100000      89.00   4539000
164         Georgia  1997           3450000      79.00   2726000
165         Georgia  1998           4200000      69.00   2898000
166         Georgia  1999           3315000      64.00   2122000
167         Georgia  2000           3135000      63.00   1975000
168         Georgia  2001           3135000      70.00   2195000
169         Georgia  2002           2600000     110.00   2860000
170         Georgia  2003           3380000     128.00   4326000
171         Georgia  2004           3087000     118.00   3643000
172         Georgia  2005           2891000      84.00   2428000
173         Georgia  2006           4662000     116.00   5408000
174         Georgia  2007           3480000     114.00   3967000
175         Georgia  2008           3905000     149.00   5818000
176         Georgia  2009           2665000     147.00   3918000
177         Georgia  2010            152000     167.00   4225000
178         Georgia  2011            196000     165.00   4612000
179         Georgia  2012            181000     192.00   5777000
180         Georgia  2013            637000     226.00   7571000
181         Georgia  2014            362000     219.00   9912000
182         Georgia  2015            221000     243.00   6707000
183         Georgia  2016            899000     269.00  10071000
184         Georgia  2017            190000     300.00   9504000
185         Georgia  2018            200000       2.76   9196000
186         Georgia  2019            370000       2.67   8987000
187         Georgia  2020            412000       2.52   8654000
188         Georgia  2021            261000       2.73   8911000
189          Hawaii  1995           1032000      55.00    568000
190          Hawaii  1996           1240000      80.00    992000
191          Hawaii  1997           1314000      86.00   1130000
192          Hawaii  1998            944000      75.00    708000
193          Hawaii  1999            640000      78.00    499000
194          Hawaii  2000            784000      81.00    635000
195          Hawaii  2001            696000      85.00    592000
196          Hawaii  2002            952000     110.00   1047000
197          Hawaii  2003            791000     143.00   1131000
198          Hawaii  2004            768000     141.00   1083000
199          Hawaii  2005           1179000     134.00   1580000
200          Hawaii  2006            930000     119.00   1107000
201          Hawaii  2007            920000     158.00   1454000
202          Hawaii  2008            900000     148.00   1332000
203          Hawaii  2009            950000     163.00   1549000
204          Hawaii  2010            239000     275.00   2118000
205          Hawaii  2011            246000     365.00   2431000
206          Hawaii  2012            263000     415.00   3113000
207          Hawaii  2013             65000     197.00   2126000
208          Hawaii  2014            140000     229.00   3195000
209          Hawaii  2015             71000     191.00   2727000
210          Hawaii  2016            127000     231.00   4176000
211          Hawaii  2017             25000     153.00   3808000
212          Hawaii  2018             18000       1.92   3362000
213          Hawaii  2019             51000       1.30   1664000
214          Hawaii  2020             79000       1.70   2678000
215          Hawaii  2021             56000       2.21   3083000
216           Idaho  1995           6000000      65.00   3900000
217           Idaho  1996           4950000      90.00   4455000
218           Idaho  1997           7680000      72.00   5530000
219           Idaho  1998           6000000      65.00   3900000
220           Idaho  1999           5760000      59.00   3398000
221           Idaho  2000           4700000      52.00   2444000
222           Idaho  2001           4600000      66.00   3036000
223           Idaho  2002           5700000     135.00   7695000
224           Idaho  2003           4600000     135.00   6210000
225           Idaho  2004           6300000     101.00   6363000
226           Idaho  2005           3515000      80.00   2812000
227           Idaho  2006           4180000      86.00   3595000
228           Idaho  2007           3772000     108.00   4074000
229           Idaho  2008           3600000     142.00   5112000
230           Idaho  2009           4738000     145.00   6870000
231           Idaho  2010           1179000     161.00   4217000
232           Idaho  2011           1879000     178.00   5575000
233           Idaho  2012            530000     163.00   4799000
234           Idaho  2013           1036000     202.00   5365000
235           Idaho  2014            850000     203.00   6902000
236           Idaho  2015           1082000     193.00   5497000
237           Idaho  2016           1253000     182.00   6002000
238           Idaho  2017           1045000     179.00   7482000
239           Idaho  2018            655000       1.96   5833000
240           Idaho  2019            677000       1.62   4769000
241           Idaho  2020            637000       1.76   6591000
242           Idaho  2021            270000       2.37   7110000
243        Illinois  1995            814000     102.00    830000
244        Illinois  1996            814000     130.00   1058000
245        Illinois  1997            483000     127.00    613000
246        Illinois  1998            639000     119.00    760000
247        Illinois  1999            594000     115.00    683000
248        Illinois  2000            488000     117.00    571000
249        Illinois  2001            456000     172.00    784000
250        Illinois  2002            720000     142.00   1022000
251        Illinois  2003            420000     173.00    727000
252        Illinois  2004            385000     193.00    743000
253        Illinois  2005            680000     162.00   1102000
254        Illinois  2006            660000     188.00   1241000
255        Illinois  2007            567000     240.00   1361000
256        Illinois  2008            448000     246.00   1102000
257        Illinois  2009            272000     226.00    615000
258        Illinois  2010             92000     278.00   1026000
259        Illinois  2011             98000     390.00   1365000
260        Illinois  2012            145000     355.00   1516000
261        Illinois  2013            101000     419.00   1408000
262        Illinois  2014             94000     411.00   1611000
263        Illinois  2015            155000     466.00   1901000
264        Illinois  2016             77000     542.00   2602000
265        Illinois  2017            167000     509.00   2576000
266        Illinois  2018            108000       4.83   2178000
267        Illinois  2019            116000       4.12   1767000
268        Illinois  2020            156000       5.65   2938000
269        Illinois  2021            115000       5.83   2682000
270         Indiana  1995            756000      68.00    514000
271         Indiana  1996            675000     107.00    722000
272         Indiana  1997            568000     113.00    642000
273         Indiana  1998            828000      85.00    704000
274         Indiana  1999            810000      90.00    729000
275         Indiana  2000            520000     103.00    536000
276         Indiana  2001            608000      86.00    523000
277         Indiana  2002            496000     114.00    565000
278         Indiana  2003            280000     159.00    445000
279         Indiana  2004            413000     158.00    653000
280         Indiana  2005            512000     119.00    609000
281         Indiana  2006            324000     151.00    489000
282         Indiana  2007            357000     139.00    496000
283         Indiana  2008            402000     161.00    647000
284         Indiana  2009            288000     198.00    570000
285         Indiana  2010            151000     223.00    959000
286         Indiana  2011            147000     214.00    873000
287         Indiana  2012            203000     254.00   1199000
288         Indiana  2013             82000     277.00    781000
289         Indiana  2014            115000     319.00    989000
290         Indiana  2015            165000     323.00   1027000
291         Indiana  2016            208000     346.00   1502000
292         Indiana  2017            158000     361.00   1502000
293         Indiana  2018            106000       3.58   1153000
294         Indiana  2019            188000       3.78   1871000
295         Indiana  2020            149000       3.91   1935000
296         Indiana  2021            177000       3.89   2023000
297            Iowa  1995           3400000      72.00   2448000
298            Iowa  1996           3886000      98.00   3808000
299            Iowa  1997           3774000      86.00   3246000
300            Iowa  1998           3900000      70.00   2730000
301            Iowa  1999           2600000      65.00   1690000
302            Iowa  2000           2010000      67.00   1347000
303            Iowa  2001           1683000      73.00   1229000
304            Iowa  2002           2310000     137.00   3165000
305            Iowa  2003           1888000     145.00   2738000